---
sidebar: sidebar 
permalink: trident-docker/collect-logs-docker.html 
keywords: deploy, Trident, trident for docker, docker, logs, binary, managed plugin 
summary: Você pode coletar registros para auxiliar na resolução de problemas.  O método que você usa para coletar os logs varia dependendo de como você está executando o plugin do Docker. 
---
= Coletar registros
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode coletar registros para auxiliar na resolução de problemas.  O método que você usa para coletar os logs varia dependendo de como você está executando o plugin do Docker.



== Colete registros para solucionar problemas.

.Passos
. Se você estiver executando o Trident usando o método de plugin gerenciado recomendado (ou seja, usando `docker plugin` comandos), veja-os da seguinte forma:
+
[source, console]
----
docker plugin ls
----
+
[listing]
----
ID                  NAME                DESCRIPTION                          ENABLED
4fb97d2b956b        netapp:latest       nDVP - NetApp Docker Volume Plugin   false
journalctl -u docker | grep 4fb97d2b956b
----
+
O nível de registro padrão deve permitir que você diagnostique a maioria dos problemas.  Se achar que isso não é suficiente, você pode ativar o registro de depuração.

. Para ativar o registro de depuração, instale o plugin com o registro de depuração ativado:
+
[source, console]
----
docker plugin install netapp/trident-plugin:<version> --alias <alias> debug=true
----
+
Ou, ative o registro de depuração quando o plugin já estiver instalado:

+
[source, console]
----
docker plugin disable <plugin>
----
+
[source, console]
----
docker plugin set <plugin> debug=true
----
+
[source, console]
----
docker plugin enable <plugin>
----
. Se você estiver executando o próprio binário no host, os logs estarão disponíveis no diretório do host. `/var/log/netappdvp` diretório.  Para ativar o registro de depuração, especifique `-debug` quando você executar o plugin.




== Dicas gerais de resolução de problemas

* O problema mais comum que os novos usuários enfrentam é uma configuração incorreta que impede a inicialização do plugin.  Quando isso acontecer, você provavelmente verá uma mensagem como esta ao tentar instalar ou ativar o plugin:
+
`Error response from daemon: dial unix /run/docker/plugins/<id>/netapp.sock: connect: no such file or directory`

+
Isso significa que o plugin não pôde ser iniciado.  Felizmente, o plugin foi desenvolvido com um recurso abrangente de registro de logs que deve ajudá-lo a diagnosticar a maioria dos problemas que você provavelmente encontrará.

* Se houver problemas com a montagem de um painel fotovoltaico em um contêiner, certifique-se de que `rpcbind` Está instalado e em funcionamento.  Utilize o gerenciador de pacotes necessário para o sistema operacional do host e verifique se `rpcbind` Está em execução.  Você pode verificar o status do serviço rpcbind executando um `systemctl status rpcbind` ou seu equivalente.

