---
sidebar: sidebar 
permalink: trident-docker/multiple-instances-docker.html 
keywords: deploy, Trident, docker, trident for docker, managed plugin, trident instances, alias 
summary: São necessárias várias instâncias do Trident quando se deseja ter várias configurações de armazenamento disponíveis simultaneamente.  A chave para múltiplas instâncias é atribuir-lhes nomes diferentes usando a opção --alias com o plugin containerizado, ou a opção --volume-driver ao instanciar o Trident no host. 
---
= Gerenciar várias instâncias do Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
São necessárias várias instâncias do Trident quando se deseja ter várias configurações de armazenamento disponíveis simultaneamente.  A chave para múltiplas instâncias é dar-lhes nomes diferentes usando o `--alias` opção com o plugin conteinerizado, ou `--volume-driver` opção ao instanciar o Trident no host.



== Etapas para o plugin gerenciado do Docker (versão 1.13/17.03 ou posterior)

. Inicie a primeira instância especificando um alias e um arquivo de configuração.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias silver netapp/trident-plugin:21.07 config=silver.json
----
. Inicie a segunda instância, especificando um alias e um arquivo de configuração diferentes.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias gold netapp/trident-plugin:21.07 config=gold.json
----
. Crie volumes especificando o alias como o nome do driver.
+
Por exemplo, para o volume de ouro:

+
[source, console]
----
docker volume create -d gold --name ntapGold
----
+
Por exemplo, para o volume de prata:

+
[source, console]
----
docker volume create -d silver --name ntapSilver
----




== Passos para a versão tradicional (1.12 ou anterior)

. Inicie o plugin com uma configuração NFS usando um ID de driver personalizado:
+
[source, console]
----
sudo trident --volume-driver=netapp-nas --config=/path/to/config-nfs.json
----
. Inicie o plugin com uma configuração iSCSI usando um ID de driver personalizado:
+
[source, console]
----
sudo trident --volume-driver=netapp-san --config=/path/to/config-iscsi.json
----
. Provisione volumes Docker para cada instância de driver:
+
Por exemplo, para NFS:

+
[source, console]
----
docker volume create -d netapp-nas --name my_nfs_vol
----
+
Por exemplo, para iSCSI:

+
[source, console]
----
docker volume create -d netapp-san --name my_iscsi_vol
----

