---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Veja as opções de configuração disponíveis para suas configurações do Trident . 
---
= Opções de configuração de armazenamento
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Veja as opções de configuração disponíveis para suas configurações do Trident .



== Opções de configuração global

Essas opções de configuração se aplicam a todas as configurações do Trident , independentemente da plataforma de armazenamento utilizada.

[cols="3*"]
|===
| Opção | Descrição | Exemplo 


| `version`  a| 
Número da versão do arquivo de configuração
 a| 
`1`



| `storageDriverName`  a| 
Nome do driver de armazenamento
 a| 
`ontap-nas`, `ontap-san` , `ontap-nas-economy` ,
`ontap-nas-flexgroup` , `solidfire-san`



| `storagePrefix`  a| 
Prefixo opcional para nomes de volumes.  Padrão: `netappdvp_` .
 a| 
`staging_`



| `limitVolumeSize`  a| 
Restrição opcional nos tamanhos dos volumes.  Padrão: "" (não aplicado)
 a| 
`10g`

|===

TIP: Não use `storagePrefix` (incluindo o padrão) para back-ends do Element.  Por padrão, o `solidfire-san` O driver irá ignorar essa configuração e não usará um prefixo.  A NetApp recomenda o uso de um tenantID específico para o mapeamento de volumes do Docker ou o uso dos dados de atributo preenchidos com a versão do Docker, informações do driver e nome bruto do Docker, nos casos em que possa ter ocorrido alguma alteração de nome.

As opções padrão estão disponíveis para evitar que você precise especificá-las em cada volume que criar.  O `size` Essa opção está disponível para todos os tipos de controladores.  Consulte a seção de configuração do ONTAP para obter um exemplo de como definir o tamanho padrão do volume.

[cols="3*"]
|===
| Opção | Descrição | Exemplo 


| `size`  a| 
Tamanho padrão opcional para novos volumes. Padrão: `1G`
 a| 
`10G`

|===


== Configuração ONTAP

Além dos valores de configuração global acima, ao usar o ONTAP, as seguintes opções de nível superior estão disponíveis.

[cols="3*"]
|===
| Opção | Descrição | Exemplo 


| `managementLIF`  a| 
Endereço IP da LIF de gerenciamento do ONTAP .  Você pode especificar um nome de domínio totalmente qualificado (FQDN).
 a| 
`10.0.0.1`



| `dataLIF`  a| 
Endereço IP do protocolo LIF.

* Drivers ONTAP NAS *: A NetApp recomenda especificar `dataLIF` .  Caso não sejam fornecidos, o Trident obtém os dataLIFs da SVM.  Você pode especificar um nome de domínio totalmente qualificado (FQDN) para ser usado nas operações de montagem NFS, permitindo criar um DNS round-robin para balancear a carga entre várias dataLIFs.

* Drivers ONTAP SAN*: Não especifique para iSCSI ou FC.  Trident usalink:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Mapa LUN Seletivo ONTAP"^] para descobrir as LIFs iSCSI ou FC necessárias para estabelecer uma sessão de múltiplos caminhos.  Um aviso é gerado se `dataLIF` está explicitamente definido.
 a| 
`10.0.0.2`



| `svm`  a| 
Máquina virtual de armazenamento a ser usada (obrigatória se a LIF de gerenciamento for uma LIF de cluster)
 a| 
`svm_nfs`



| `username`  a| 
Nome de usuário para conectar-se ao dispositivo de armazenamento
 a| 
`vsadmin`



| `password`  a| 
Senha para conectar ao dispositivo de armazenamento
 a| 
`secret`



| `aggregate`  a| 
Agregado para provisionamento (opcional; se definido, deve ser atribuído à SVM).  Para o `ontap-nas-flexgroup` motorista, esta opção é ignorada.  Todos os agregados atribuídos ao SVM são usados ​​para provisionar um volume FlexGroup .
 a| 
`aggr1`



| `limitAggregateUsage`  a| 
Opcional: o provisionamento pode falhar se a utilização for superior a esta percentagem.
 a| 
`75%`



| `nfsMountOptions`  a| 
Controle preciso das opções de montagem NFS; o padrão é "-o nfsvers=3".  *Disponível apenas para o `ontap-nas` e `ontap-nas-economy` motoristas*. https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Consulte as informações de configuração do host NFS aqui."^] .
 a| 
`-o nfsvers=4`



| `igroupName`  a| 
O Trident cria e gerencia por nó. `igroups` como `netappdvp` .

Este valor não pode ser alterado nem omitido.

*Disponível apenas para o `ontap-san` motorista*.
 a| 
`netappdvp`



| `limitVolumeSize`  a| 
Tamanho máximo do volume solicitado.
 a| 
`300g`



| `qtreesPerFlexvol`  a| 
Número máximo de qtrees por FlexVol, deve estar no intervalo [50, 300], o padrão é 200.

*Para o `ontap-nas-economy` driver, esta opção permite personalizar o número máximo de qtrees por FlexVol*.
 a| 
`300`



 a| 
`sanType`
| *Compatível com `ontap-san` Somente o motorista.*  Use para selecionar `iscsi` para iSCSI, `nvme` para NVMe/TCP ou `fcp` para SCSI sobre Fibre Channel (FC). | `iscsi`se estiver em branco 


| `limitVolumePoolSize` | *Compatível com `ontap-san-economy` e `ontap-san-economy` Somente motoristas.*  Limita os tamanhos do FlexVol nos drivers ONTAP ontap-nas-economy e ontap-SAN-economy.  a| 
`300g`

|===
As opções padrão estão disponíveis para evitar que você precise especificá-las em cada volume que criar:

[cols="1,3,2"]
|===
| Opção | Descrição | Exemplo 


| `spaceReserve`  a| 
Modo de reserva de espaço; `none` (provisionamento dinâmico) ou `volume` (espesso)
 a| 
`none`



| `snapshotPolicy`  a| 
A política de instantâneo a ser usada, padrão é `none`
 a| 
`none`



| `snapshotReserve`  a| 
Percentual de reserva de snapshots; o padrão é "" para aceitar o padrão do ONTAP.
 a| 
`10`



| `splitOnClone`  a| 
Separar um clone de seu pai no momento da criação; o padrão é `false`
 a| 
`false`



| `encryption`  a| 
Habilita a Criptografia de Volume NetApp (NVE) no novo volume; o padrão é `false` .  Para usar esta opção, o NVE precisa estar licenciado e habilitado no cluster.

Se o NAE estiver habilitado no backend, qualquer volume provisionado no Trident terá o NAE habilitado.

Para mais informações, consulte:link:../trident-reco/security-reco.html["Como o Trident funciona com NVE e NAE"] .
 a| 
verdadeiro



| `unixPermissions`  a| 
Opção NAS para volumes NFS provisionados, o padrão é `777`
 a| 
`777`



| `snapshotDir`  a| 
Opção NAS para acesso ao `.snapshot` diretório.
 a| 
"verdadeiro" para NFSv4 "falso" para NFSv3



| `exportPolicy`  a| 
Opção NAS para a política de exportação NFS a ser usada, o padrão é `default`
 a| 
`default`



| `securityStyle`  a| 
Opção NAS para acesso ao volume NFS provisionado.

Suporte a NFS `mixed` e `unix` estilos de segurança.  O padrão é `unix` .
 a| 
`unix`



| `fileSystemType`  a| 
Opção SAN para selecionar o tipo de sistema de arquivos; o padrão é `ext4`
 a| 
`xfs`



| `tieringPolicy`  a| 
A política de hierarquização a ser usada, padrão é `none` .
 a| 
`none`

|===


=== Opções de escala

O `ontap-nas` e `ontap-san` Os drivers criam um ONTAP FlexVol para cada volume Docker.  O ONTAP suporta até 1000 FlexVols por nó de cluster, com um máximo de 12.000 volumes FlexVol por cluster. Se os seus requisitos de volume do Docker estiverem dentro dessa limitação, o `ontap-nas` O driver é a solução NAS preferida devido aos recursos adicionais oferecidos pelo FlexVols, como snapshots granulares de volume Docker e clonagem.

Se você precisar de mais volumes Docker do que os limites do FlexVol permitem, escolha a opção `ontap-nas-economy` ou o `ontap-san-economy` motorista.

O `ontap-nas-economy` O driver cria volumes Docker como Qtrees ONTAP dentro de um conjunto de volumes FlexVol gerenciados automaticamente.  As Qtrees oferecem uma escalabilidade muito maior, até 100.000 por nó de cluster e 2.400.000 por cluster, à custa de algumas funcionalidades.  O `ontap-nas-economy` O driver não suporta snapshots granulares de volume do Docker nem clonagem.


NOTE: O `ontap-nas-economy` O driver não é suportado atualmente no Docker Swarm, pois o Docker Swarm não orquestra a criação de volumes em vários nós.

O `ontap-san-economy` O driver cria volumes Docker como LUNs ONTAP dentro de um pool compartilhado de volumes FlexVol gerenciados automaticamente.  Dessa forma, cada FlexVol não fica restrito a apenas um LUN, oferecendo melhor escalabilidade para cargas de trabalho SAN.  Dependendo do array de armazenamento, o ONTAP suporta até 16384 LUNs por cluster.  Como os volumes são LUNs subjacentes, este driver suporta snapshots e clonagem granulares de volume do Docker.

Escolha o `ontap-nas-flexgroup` Driver para aumentar o paralelismo em um único volume que pode crescer até a faixa de petabytes com bilhões de arquivos.  Alguns casos de uso ideais para FlexGroups incluem IA/ML/DL, big data e análise de dados, compilação de software, streaming, repositórios de arquivos e assim por diante.  O Trident utiliza todos os agregados atribuídos a uma SVM ao provisionar um volume FlexGroup .  O suporte do FlexGroup no Trident também leva em consideração os seguintes aspectos:

* Requer ONTAP versão 9.2 ou superior.
* Até o momento da redação deste texto, o FlexGroups suporta apenas NFS v3.
* Recomenda-se habilitar os identificadores NFSv3 de 64 bits para a SVM.
* O tamanho mínimo recomendado do membro/volume do FlexGroup é 100 GiB.
* A clonagem não é suportada para volumes FlexGroup .


Para obter informações sobre FlexGroups e cargas de trabalho adequadas para FlexGroups, consulte o seguinte: https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["Guia de Melhores Práticas e Implementação do NetApp FlexGroup para volumes"^] .

Para obter recursos avançados e grande escalabilidade no mesmo ambiente, você pode executar várias instâncias do Docker Volume Plugin, com uma delas usando `ontap-nas` e outro usando `ontap-nas-economy` .



=== Função ONTAP personalizada para Trident

Você pode criar uma função de cluster ONTAP com privilégios mínimos para que não precise usar a função de administrador do ONTAP para executar operações no Trident.  Ao incluir o nome de usuário em uma configuração de backend do Trident , o Trident usa a função de cluster ONTAP que você criou para executar as operações.

Consultelink:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Gerador de funções personalizadas Trident"] Para obter mais informações sobre como criar funções personalizadas do Trident .

[role="tabbed-block"]
====
.Utilizando a CLI do ONTAP
--
. Crie uma nova função usando o seguinte comando:
+
`security login role create <role_name\> -cmddirname "command" -access all -vserver <svm_name\>`

. Crie um nome de usuário para o usuário do Trident :
+
`security login create -username <user_name\> -application ontapi -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`
`security login create -username <user_name\> -application http -authmethod password -role <name_of_role_in_step_1\> -vserver <svm_name\> -comment "user_description"`

. Atribua a função ao usuário:
+
`security login modify username <user_name\> -vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.Utilizando o Gerenciador de Sistemas
--
Execute as seguintes etapas no ONTAP System Manager:

. *Criar uma função personalizada*:
+
.. Para criar uma função personalizada no nível do cluster, selecione *Cluster > Configurações*.
+
(Ou) Para criar uma função personalizada no nível da SVM, selecione *Armazenamento > VMs de armazenamento > `required SVM` > Configurações > Usuários e funções*.

.. Selecione o ícone de seta (*->*) ao lado de *Usuários e Funções*.
.. Selecione *+Adicionar* em *Funções*.
.. Defina as regras para a função e clique em *Salvar*.


. *Atribua a função ao usuário do Trident *: + Execute as seguintes etapas na página *Usuários e Funções*:
+
.. Selecione o ícone Adicionar *** em *Usuários*.
.. Selecione o nome de usuário desejado e, em seguida, selecione uma função no menu suspenso *Função*.
.. Clique em *Salvar*.




--
====
Consulte as páginas seguintes para obter mais informações:

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["Funções personalizadas para administração do ONTAP"^]oulink:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["Defina funções personalizadas"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["Trabalhar com funções e usuários"^]




=== Arquivos de configuração de exemplo do ONTAP

.Exemplo de NFS para o driver <code>ontap-nas</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "defaults": {
    "size": "10G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.Exemplo de NFS para o driver <code>ontap-nas-flexgroup</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-flexgroup",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "defaults": {
    "size": "100G",
    "spaceReserve": "none",
    "exportPolicy": "default"
  }
}
----
====
.Exemplo de NFS para o driver <code>ontap-nas-economy</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-nas-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1"
}
----
====
.Exemplo de iSCSI para o driver ontap-san.
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.Exemplo de NFS para o driver <code>ontap-san-economy</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "storageDriverName": "ontap-san-economy",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.3",
  "svm": "svm_iscsi_eco",
  "username": "vsadmin",
  "password": "password",
  "aggregate": "aggr1",
  "igroupName": "netappdvp"
}
----
====
.Exemplo NVMe/TCP para o driver ontap-san.
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "NVMeBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nvme",
  "username": "vsadmin",
  "password": "password",
  "sanType": "nvme",
  "useREST": true
}
----
====
.Exemplo de SCSI sobre FC para o driver <code>ontap-san</code>
[%collapsible]
====
[source, json]
----
{
  "version": 1,
  "backendName": "ontap-san-backend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "sanType": "fcp",
  "svm": "trident_svm",
  "username": "vsadmin",
  "password": "password",
  "useREST": true
}
----
====


== Configuração do software Element

Além dos valores de configuração global, ao usar o software Element (NetApp HCI/ SolidFire), estas opções estão disponíveis.

[cols="3*"]
|===
| Opção | Descrição | Exemplo 


| `Endpoint`  a| 
https://<login>:<senha>@<mvip>/json-rpc/<element-version>
 a| 
https://admin:admin@192.168.160.3/json-rpc/8.0



| `SVIP`  a| 
Endereço IP e porta iSCSI
 a| 
10.0.0.7:3260



| `TenantName`  a| 
Tenant do SolidFireF a ser usado (criado se não for encontrado)
 a| 
`docker`



| `InitiatorIFace`  a| 
Especifique a interface ao restringir o tráfego iSCSI a uma interface não padrão.
 a| 
`default`



| `Types`  a| 
Especificações de QoS
 a| 
Veja o exemplo abaixo.



| `LegacyNamePrefix`  a| 
Prefixo para instalações Trident atualizadas.  Se você utilizou uma versão do Trident anterior à 1.3.2 e realizar uma atualização com volumes existentes, será necessário definir esse valor para acessar seus volumes antigos que foram mapeados pelo método de nome do volume.
 a| 
`netappdvp-`

|===
O `solidfire-san` O driver não é compatível com o Docker Swarm.



=== Exemplo de arquivo de configuração do software Element

[source, json]
----
{
  "version": 1,
  "storageDriverName": "solidfire-san",
  "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
  "SVIP": "10.0.0.7:3260",
  "TenantName": "docker",
  "InitiatorIFace": "default",
  "Types": [
    {
      "Type": "Bronze",
      "Qos": {
        "minIOPS": 1000,
        "maxIOPS": 2000,
        "burstIOPS": 4000
      }
    },
    {
      "Type": "Silver",
      "Qos": {
        "minIOPS": 4000,
        "maxIOPS": 6000,
        "burstIOPS": 8000
      }
    },
    {
      "Type": "Gold",
      "Qos": {
        "minIOPS": 6000,
        "maxIOPS": 8000,
        "burstIOPS": 10000
      }
    }
  ]
}
----