---
sidebar: sidebar 
permalink: faq.html 
keywords: faq, frequently asked questions 
summary: Encontre respostas para as perguntas mais frequentes sobre instalação, configuração, atualização e resolução de problemas do Trident. 
---
= Perguntas frequentes
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Encontre respostas para as perguntas mais frequentes sobre instalação, configuração, atualização e resolução de problemas do Trident.



[[general-questions]]
== Perguntas gerais



[[how-frequently-is-trident-released]]
=== Com que frequência o Trident é lançado?

A partir da versão 24.02, o Trident passa a ser lançado a cada quatro meses: fevereiro, junho e outubro.



[[does-trident-support-all-the-features-that-are-released-in-a-particular-version-of-kubernetes]]
=== O Trident é compatível com todos os recursos lançados em uma determinada versão do Kubernetes?

O Trident geralmente não oferece suporte a recursos alfa no Kubernetes.  O Trident poderá oferecer suporte a recursos beta nas duas versões do Trident que seguem a versão beta do Kubernetes.



[[does-trident-have-any-dependencies-on-other-netapp-products-for-its-functioning]]
=== O Trident depende de outros produtos da NetApp para funcionar?

O Trident não possui dependências de outros produtos de software da NetApp e funciona como um aplicativo independente.  No entanto, você deve ter um dispositivo de armazenamento de backend da NetApp .



[[how-can-i-obtain-complete-trident-configuration-details]]
=== Como posso obter detalhes completos da configuração do Trident ?

Use o `tridentctl get` comando para obter mais informações sobre a sua configuração do Trident .



[[can-i-obtain-metrics-on-how-storage-is-provisioned-by-trident]]
=== Posso obter métricas sobre como o armazenamento é provisionado pelo Trident?

Sim. Os endpoints do Prometheus podem ser usados ​​para coletar informações sobre a operação do Trident , como o número de backends gerenciados, o número de volumes provisionados, bytes consumidos e assim por diante.  Você também pode usarlink:https://docs.netapp.com/us-en/cloudinsights/["Cloud Insights"^] para monitoramento e análise.



[[does-the-user-experience-change-when-using-trident-as-a-csi-provisioner]]
=== A experiência do usuário muda ao usar o Trident como um provisionador CSI?

Não. Não haverá alterações em termos de experiência do usuário e funcionalidades.  O nome do provisionador utilizado é `csi.trident.netapp.io` .  Este método de instalação do Trident é recomendado se você deseja usar todos os novos recursos oferecidos pelas versões atuais e futuras.



[[install-and-use-trident-on-a-kubernetes-cluster]]
== Instale e utilize o Trident em um cluster Kubernetes.



[[does-trident-support-an-offline-install-from-a-private-registry]]
=== O Trident suporta instalação offline a partir de um registro privado?

Sim, Trident pode ser instalado offline. Consulte link:trident-install/kubernetes-deploy.html["Saiba mais sobre a instalação do Trident."^].



[[can-i-install-trident-be-remotely]]
=== Posso instalar o Trident remotamente?

Sim. O Trident 18.10 e versões posteriores suportam a capacidade de instalação remota a partir de qualquer máquina que possua `kubectl` Acesso ao cluster.  Depois `kubectl` O acesso é verificado (por exemplo, iniciar um `kubectl get nodes` comando da máquina remota para verificar), siga as instruções de instalação.



[[can-i-configure-high-availability-with-trident]]
=== Posso configurar alta disponibilidade com o Trident?

O Trident é instalado como um Deployment do Kubernetes (ReplicaSet) com uma única instância, portanto, possui alta disponibilidade integrada. Você não deve aumentar o número de réplicas no deployment.  Se o nó onde o Trident está instalado for perdido ou o pod ficar inacessível por qualquer outro motivo, o Kubernetes reimplantará automaticamente o pod em um nó íntegro do cluster.  O Trident é apenas um sistema de controle de voo, portanto, os pods atualmente instalados não serão afetados se o Trident for reimplantado.



[[does-trident-need-access-to-the-kube-system-namespace]]
=== O Trident precisa de acesso ao namespace kube-system?

O Trident lê dados do servidor da API do Kubernetes para determinar quando os aplicativos solicitam novos PVCs, portanto, ele precisa de acesso ao kube-system.



[[what-are-the-roles-and-privileges-used-by-trident]]
=== Quais são as funções e privilégios utilizados pela Trident?

O instalador do Trident cria um Kubernetes ClusterRole, que tem acesso específico aos PersistentVolume, PersistentVolumeClaim, StorageClass e recursos Secret do cluster Kubernetes. Consulte link:trident-install/kubernetes-customize-deploy-tridentctl.html["Personalize a instalação do tridentctl"].



[[can-i-locally-generate-the-exact-manifest-files-trident-uses-for-installation]]
=== Posso gerar localmente os mesmos arquivos de manifesto que o Trident usa para a instalação?

Você pode gerar e modificar localmente os arquivos de manifesto exatos que o Trident usa para instalação, se necessário. Consulte link:trident-install/kubernetes-customize-deploy-tridentctl.html["Personalize a instalação do tridentctl"].



[[can-i-share-the-same-ontap-backend-svm-for-two-separate-trident-instances-for-two-separate-kubernetes-clusters]]
=== Posso compartilhar a mesma SVM de backend ONTAP para duas instâncias Trident separadas em dois clusters Kubernetes distintos?

Embora não seja recomendável, você pode usar o mesmo SVM de backend para duas instâncias do Trident .  Especifique um nome de volume exclusivo para cada instância durante a instalação e/ou especifique um valor exclusivo. `StoragePrefix` parâmetro no `setup/backend.json` arquivo.  Isso garante que o mesmo FlexVol volume não seja usado para ambas as instâncias.



[[is-it-possible-to-install-trident-under-containerlinux-formerly-coreos]]
=== É possível instalar o Trident no ContainerLinux (anteriormente CoreOS)?

O Trident é simplesmente um pod do Kubernetes e pode ser instalado em qualquer lugar onde o Kubernetes esteja em execução.



[[can-i-use-trident-with-netapp-cloud-volumes-ontap]]
=== Posso usar o Trident com o NetApp Cloud Volumes ONTAP?

Sim, o Trident é compatível com AWS, Google Cloud e Azure.



[[does-trident-work-with-cloud-volumes-services]]
=== O Trident funciona com o Cloud Volumes Services?

Sim, o Trident é compatível com o serviço Azure NetApp Files no Azure, bem como com o Cloud Volumes Service no GCP.



[[troubleshooting-and-support]]
== Solução de problemas e suporte



[[does-netapp-support-trident]]
=== A NetApp oferece suporte ao Trident?

Embora o Trident seja de código aberto e fornecido gratuitamente, a NetApp oferece suporte completo, desde que seu sistema NetApp seja compatível.



[[how-do-i-raise-a-support-case]]
=== Como faço para abrir um chamado de suporte?

Para abrir um chamado de suporte, faça um dos seguintes procedimentos:

. Entre em contato com seu Gerente de Suporte e obtenha ajuda para abrir um chamado.
. Abra um chamado de suporte entrando em contato com https://www.netapp.com/company/contact-us/support/["Suporte NetApp"^] .




[[how-do-i-generate-a-support-log-bundle]]
=== Como faço para gerar um pacote de logs de suporte?

Você pode criar um pacote de suporte executando o seguinte comando: `tridentctl logs -a` .  Além dos logs capturados no pacote, capture também o log do kubelet para diagnosticar problemas de montagem no lado do Kubernetes.  As instruções para obter o log do kubelet variam dependendo de como o Kubernetes foi instalado.



[[what-do-i-do-if-i-need-to-raise-a-request-for-a-new-feature]]
=== O que devo fazer se precisar solicitar uma nova funcionalidade?

Crie um problema em https://github.com/NetApp/trident["Trident Github"^] e mencione *RFE* no assunto e na descrição do problema.



[[where-do-i-raise-a-defect]]
=== Onde posso reportar um defeito?

Crie um problema em https://github.com/NetApp/trident["Trident Github"^] .  Certifique-se de incluir todas as informações e registros necessários referentes ao problema.



[[what-happens-if-i-have-quick-question-on-trident-that-i-need-clarification-on-is-there-a-community-or-a-forum]]
=== O que acontece se eu tiver uma pergunta rápida sobre o Trident que precise de esclarecimento?  Existe alguma comunidade ou fórum?

Se você tiver alguma dúvida, problema ou solicitação, entre em contato conosco através do nosso Trident.link:https://discord.gg/NetApp["Canal do Discord"^] ou GitHub.



[[my-storage-systems-password-has-changed-and-trident-no-longer-works-how-do-i-recover]]
=== A senha do meu sistema de armazenamento foi alterada e o Trident não funciona mais. Como faço para recuperar o sistema?

Atualize a senha do backend com `tridentctl update backend myBackend -f </path/to_new_backend.json> -n trident` .  Substituir `myBackend` no exemplo com o nome do seu backend, e ``/path/to_new_backend.json` com o caminho para o correto `backend.json` arquivo.



[[trident-cannot-find-my-kubernetes-node-how-do-i-fix-this]]
=== O Trident não consegue encontrar meu nó Kubernetes.  Como posso resolver isso?

Existem dois cenários prováveis ​​para o Trident não conseguir encontrar um nó do Kubernetes.  Isso pode ser devido a um problema de rede no Kubernetes ou a um problema de DNS.  O daemonset do nó Trident que é executado em cada nó do Kubernetes deve ser capaz de se comunicar com o controlador Trident para registrar o nó no Trident.  Se ocorreram alterações na rede após a instalação do Trident , você encontrará esse problema apenas com novos nós do Kubernetes adicionados ao cluster.



[[if-the-trident-pod-is-destroyed-will-i-lose-the-data]]
=== Se a cápsula Trident for destruída, perderei os dados?

Os dados não serão perdidos se a cápsula Trident for destruída.  Os metadados do Trident são armazenados em objetos CRD.  Todos os sistemas fotovoltaicos (PVs) provisionados pela Trident funcionarão normalmente.



[[upgrade-trident]]
== Trident aprimorado



[[can-i-upgrade-from-a-older-version-directly-to-a-newer-version-skipping-a-few-versions]]
=== Posso atualizar diretamente de uma versão antiga para uma versão mais recente (pulando algumas versões)?

A NetApp oferece suporte à atualização do Trident de uma versão principal para a próxima versão principal imediata.  Você pode atualizar da versão 18.xx para a 19.xx, da 19.xx para a 20.xx e assim por diante.  Você deve testar a atualização em um ambiente de laboratório antes de implementá-la em produção.



[[is-it-possible-to-downgrade-trident-to-a-previous-release]]
=== É possível fazer o downgrade do Trident para uma versão anterior?

Se você precisar de correções para erros observados após uma atualização, problemas de dependência ou uma atualização malsucedida ou incompleta, você develink:trident-managing-k8s/uninstall-trident.html["Desinstalar Trident"] e reinstale a versão anterior seguindo as instruções específicas para essa versão.  Esta é a única maneira recomendada de fazer o downgrade para uma versão anterior.



[[manage-backends-and-volumes]]
== Gerenciar back-ends e volumes



[[do-i-need-to-define-both-management-and-datalifs-in-an-ontap-backend-definition-file]]
=== Preciso definir tanto o Management quanto o DataLIF no mesmo arquivo de definição do backend ONTAP ?

A gestão do LIF é obrigatória.  O DataLIF varia:

* ONTAP SAN: Não especifique para iSCSI.  Trident usalink:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["Mapa LUN Seletivo ONTAP"^] Descobrir os LIFs iSCI necessários para estabelecer uma sessão de múltiplos caminhos.  Um aviso é gerado se `dataLIF` está explicitamente definido. Consulte link:trident-use/ontap-san-examples.html["Opções e exemplos de configuração do ONTAP SAN"] para mais detalhes.
* ONTAP NAS: A NetApp recomenda especificar `dataLIF` .  Caso não sejam fornecidos, o Trident obtém os dataLIFs da SVM.  Você pode especificar um nome de domínio totalmente qualificado (FQDN) para ser usado nas operações de montagem NFS, permitindo criar um DNS round-robin para balancear a carga entre várias dataLIFs.  Consultelink:trident-use/ontap-nas-examples.html["Opções e exemplos de configuração do ONTAP NAS"] para detalhes




[[can-trident-configure-chap-for-ontap-backends]]
=== O Trident consegue configurar CHAP para backends ONTAP ?

Sim. O Trident oferece suporte a CHAP bidirecional para backends ONTAP .  Isso requer configuração. `useCHAP=true` na sua configuração de backend.



[[how-do-i-manage-export-policies-with-trident]]
=== Como faço para gerenciar políticas de exportação com o Trident?

O Trident pode criar e gerenciar políticas de exportação dinamicamente a partir da versão 20.04.  Isso permite que o administrador de armazenamento forneça um ou mais blocos CIDR em sua configuração de backend e que o Trident adicione os IPs dos nós que se enquadram nesses intervalos a uma política de exportação criada por ele.  Dessa forma, o Trident gerencia automaticamente a adição e a exclusão de regras para nós com IPs dentro dos CIDRs especificados.



[[can-ipv6-addresses-be-used-for-the-management-and-datalifs]]
=== É possível usar endereços IPv6 para as LIFs de gerenciamento e de dados?

O Trident suporta a definição de endereços IPv6 para:

* `managementLIF`e `dataLIF` para backends ONTAP NAS.
* `managementLIF`para backends SAN ONTAP .  Você não pode especificar `dataLIF` em um backend ONTAP SAN.


O Trident deve ser instalado usando a flag `--use-ipv6` (para `tridentctl` instalação), `IPv6` (para operador Trident ), ou `tridentTPv6` (para instalação do Helm) para que funcione em IPv6.



[[is-it-possible-to-update-the-management-lif-on-the-backend]]
=== É possível atualizar o LIF de gerenciamento no backend?

Sim, é possível atualizar o LIF de gerenciamento do backend usando o `tridentctl update backend` comando.



[[is-it-possible-to-update-the-datalif-on-the-backend]]
=== É possível atualizar o DataLIF no backend?

Você pode atualizar o DataLIF em `ontap-nas` e `ontap-nas-economy` apenas.



[[can-i-create-multiple-backends-in-trident-for-kubernetes]]
=== Posso criar vários backends no Trident para Kubernetes?

O Trident pode suportar vários backends simultaneamente, seja com o mesmo driver ou com drivers diferentes.



[[how-does-trident-store-backend-credentials]]
=== Como o Trident armazena as credenciais do backend?

O Trident armazena as credenciais do backend como segredos do Kubernetes.



[[how-does-trident-select-a-specific-backend]]
=== Como o Trident seleciona um backend específico?

Se os atributos de backend não puderem ser usados para selecionar automaticamente os pools corretos para uma classe, o `storagePools` e `additionalStoragePools` Os parâmetros são usados para selecionar um conjunto específico de pools.



[[how-do-i-ensure-that-trident-will-not-provision-from-a-specific-backend]]
=== Como posso garantir que o Trident não provisione a partir de um backend específico?

O `excludeStoragePools` O parâmetro é usado para filtrar o conjunto de pools que o Trident usa para provisionamento e removerá quaisquer pools que correspondam.



[[if-there-are-multiple-backends-of-the-same-kind-how-does-trident-select-which-backend-to-use]]
=== Se existirem vários backends do mesmo tipo, como o Trident seleciona qual backend usar?

Se houver vários backends configurados do mesmo tipo, o Trident seleciona o backend apropriado com base nos parâmetros presentes em `StorageClass` e `PersistentVolumeClaim` .  Por exemplo, se houver vários backends de driver ontap-nas, o Trident tenta corresponder aos parâmetros no `StorageClass` e `PersistentVolumeClaim` combinados e compatíveis com um backend que possa atender aos requisitos listados em `StorageClass` e `PersistentVolumeClaim` .  Se houver vários servidores de backend que correspondam à solicitação, o Trident selecionará um deles aleatoriamente.



[[does-trident-support-bi-directional-chap-with-elementsolidfire]]
=== O Trident suporta CHAP bidirecional com Element/ SolidFire?

Sim.



[[how-does-trident-deploy-qtrees-on-an-ontap-volume-how-many-qtrees-can-be-deployed-on-a-single-volume]]
=== Como o Trident implementa Qtrees em um volume ONTAP ?  Quantas Qtrees podem ser implantadas em um único volume?

O `ontap-nas-economy` O driver cria até 200 Qtrees no mesmo FlexVol volume (configurável entre 50 e 300), 100.000 Qtrees por nó de cluster e 2,4 milhões por cluster.  Ao inserir um novo `PersistentVolumeClaim` que é atendido pelo driver de economia, o driver verifica se já existe um FlexVol volume que possa atender à nova Qtree.  Caso não exista um FlexVol volume capaz de atender à Qtree, um novo FlexVol volume será criado.



[[how-can-i-set-unix-permissions-for-volumes-provisioned-on-ontap-nas]]
=== Como posso configurar as permissões Unix para volumes provisionados em um NAS ONTAP ?

Você pode definir permissões Unix no volume provisionado pelo Trident configurando um parâmetro no arquivo de definição do backend.



[[how-can-i-configure-an-explicit-set-of-ontap-nfs-mount-options-while-provisioning-a-volume]]
=== Como posso configurar um conjunto explícito de opções de montagem NFS do ONTAP durante o provisionamento de um volume?

Por padrão, o Trident não define opções de montagem com nenhum valor no Kubernetes.  Para especificar as opções de montagem na classe de armazenamento do Kubernetes, siga o exemplo fornecido.link:https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-ontapnas-k8s1.8-mountoptions.yaml["aqui"^] .



[[how-do-i-set-the-provisioned-volumes-to-a-specific-export-policy]]
=== Como faço para definir os volumes provisionados para uma política de exportação específica?

Para permitir que os hosts apropriados acessem um volume, use o `exportPolicy` parâmetro configurado no arquivo de definição do backend.



[[how-do-i-set-volume-encryption-through-trident-with-ontap]]
=== Como faço para configurar a criptografia de volume através do Trident com o ONTAP?

Você pode configurar a criptografia no volume provisionado pelo Trident usando o parâmetro de criptografia no arquivo de definição do backend.  Para mais informações, consulte:link:trident-reco/security-reco.html#use-trident-with-nve-and-nae["Como o Trident funciona com NVE e NAE"]



[[what-is-the-best-way-to-implement-qos-for-ontap-through-trident]]
=== Qual a melhor forma de implementar QoS para ONTAP através do Trident?

Usar `StorageClasses` Implementar QoS para ONTAP.



[[how-do-i-specify-thin-or-thick-provisioning-through-trident]]
=== Como posso especificar provisionamento fino ou espesso através do Trident?

Os drivers ONTAP suportam provisionamento fino ou provisionamento espesso.  Os drivers ONTAP utilizam, por padrão, o provisionamento dinâmico (thin provisioning).  Se desejar provisionamento espesso, você deve configurar o arquivo de definição do backend ou o `StorageClass` .  Se ambos estiverem configurados, `StorageClass` tem precedência.  Configure o seguinte para o ONTAP:

. Sobre `StorageClass` , defina o `provisioningType` atributo como espesso.
. No arquivo de definição do backend, habilite volumes espessos definindo `backend spaceReserve parameter` como volume.




[[how-do-i-make-sure-that-the-volumes-being-used-are-not-deleted-even-if-i-accidentally-delete-the-pvc]]
=== Como posso garantir que os volumes em uso não sejam excluídos mesmo se eu excluir acidentalmente o PVC?

A proteção contra PVCs é ativada automaticamente no Kubernetes a partir da versão 1.10.



[[can-i-grow-nfs-pvcs-that-were-created-by-trident]]
=== Posso cultivar PVCs NFS criados pela Trident?

Sim. Você pode expandir um tubo de PVC que foi criado pela Trident.  Note que o crescimento automático de volume é um recurso do ONTAP que não se aplica ao Trident.



[[can-i-import-a-volume-while-it-is-in-snapmirror-data-protection-dp-or-offline-mode]]
=== Posso importar um volume enquanto ele estiver no modo de Proteção de Dados (DP) do SnapMirror ou no modo offline?

A importação do volume falha se o volume externo estiver no modo DP ou estiver offline.  Você recebe a seguinte mensagem de erro:

[listing]
----
Error: could not import volume: volume import failed to get size of volume: volume <name> was not found (400 Bad Request) command terminated with exit code 1.
Make sure to remove the DP mode or put the volume online before importing the volume.
----


[[how-is-resource-quota-translated-to-a-netapp-cluster]]
=== Como a quota de recursos é traduzida em um cluster NetApp ?

A cota de recursos de armazenamento do Kubernetes deve funcionar enquanto houver capacidade disponível no armazenamento da NetApp .  Quando o armazenamento NetApp não consegue respeitar as configurações de cota do Kubernetes devido à falta de capacidade, o Trident tenta provisionar, mas ocorre um erro.



[[can-i-create-volume-snapshots-using-trident]]
=== Posso criar snapshots de volume usando o Trident?

Sim. O Trident oferece suporte à criação de snapshots de volumes sob demanda e volumes persistentes a partir de snapshots.  Para criar PVs a partir de snapshots, certifique-se de que o `VolumeSnapshotDataSource` O recurso de bloqueio foi ativado.



[[what-are-the-drivers-that-support-trident-volume-snapshots]]
=== Quais são os drivers que suportam snapshots de volume do Trident ?

A partir de hoje, o suporte para snapshots sob demanda está disponível para nossos produtos. `ontap-nas` , `ontap-nas-flexgroup` , `ontap-san` , `ontap-san-economy` , `solidfire-san` , `gcp-cvs` , e `azure-netapp-files` Drivers de backend.



[[how-do-i-take-a-snapshot-backup-of-a-volume-provisioned-by-trident-with-ontap]]
=== Como faço para criar um backup instantâneo de um volume provisionado pelo Trident com o ONTAP?

Isso está disponível em `ontap-nas` , `ontap-san` , e `ontap-nas-flexgroup` motoristas.  Você também pode especificar um `snapshotPolicy` para o `ontap-san-economy` driver no nível FlexVol .

Isso também está disponível em `ontap-nas-economy` drivers, mas na granularidade do nível de FlexVol volume e não na granularidade do nível de qtree.  Para habilitar a capacidade de criar snapshots de volumes provisionados pelo Trident, defina a opção de parâmetro de backend. `snapshotPolicy` para a política de snapshots desejada, conforme definida no backend ONTAP .  O Trident não tem conhecimento de quaisquer instantâneos capturados pelo controlador de armazenamento.



[[can-i-set-a-snapshot-reserve-percentage-for-a-volume-provisioned-through-trident]]
=== Posso definir uma porcentagem de reserva de snapshots para um volume provisionado através do Trident?

Sim, você pode reservar uma porcentagem específica de espaço em disco para armazenar as cópias de snapshots por meio do Trident , definindo a configuração. `snapshotReserve` atributo no arquivo de definição do backend.  Se você configurou `snapshotPolicy` e `snapshotReserve` No arquivo de definição do backend, a porcentagem de reserva de snapshots é definida de acordo com o `snapshotReserve` porcentagem mencionada no arquivo de backend.  Se o `snapshotReserve` A porcentagem não é mencionada; por padrão, o ONTAP considera 5% para a reserva de snapshots.  Se o `snapshotPolicy` A opção está definida como nenhuma e a porcentagem de reserva de instantâneo está definida como 0.



[[can-i-directly-access-the-volume-snapshot-directory-and-copy-files]]
=== Posso acessar diretamente o diretório de snapshots do volume e copiar arquivos?

Sim, você pode acessar o diretório de snapshots no volume provisionado pelo Trident definindo o `snapshotDir` parâmetro no arquivo de definição do backend.



[[can-i-set-up-snapmirror-for-volumes-through-trident]]
=== Posso configurar o SnapMirror para volumes através do Trident?

Atualmente, o SnapMirror precisa ser configurado externamente usando a CLI do ONTAP ou o OnCommand System Manager.



[[how-do-i-restore-persistent-volumes-to-a-specific-ontap-snapshot]]
=== Como faço para restaurar volumes persistentes para um snapshot específico do ONTAP ?

Para restaurar um volume para um snapshot do ONTAP , execute os seguintes passos:

. Suspenda o pod da aplicação que está utilizando o volume persistente.
. Retorne ao snapshot desejado através da CLI do ONTAP ou do OnCommand System Manager.
. Reinicie o pod da aplicação.




[[can-trident-provision-volumes-on-svms-that-have-a-load-sharing-mirror-configured]]
=== O Trident consegue provisionar volumes em SVMs que tenham um espelhamento de compartilhamento de carga configurado?

É possível criar espelhos de balanceamento de carga para volumes raiz de SVMs que fornecem dados via NFS.  O ONTAP atualiza automaticamente os espelhos de balanceamento de carga para volumes que foram criados pelo Trident.  Isso pode resultar em atrasos na montagem dos volumes.  Quando vários volumes são criados usando o Trident, o provisionamento de um volume depende da atualização do espelho de balanceamento de carga ONTAP .



[[how-can-i-separate-out-storage-class-usage-for-each-customertenant]]
=== Como posso separar o uso de classes de armazenamento para cada cliente/inquilino?

O Kubernetes não permite classes de armazenamento em namespaces.  No entanto, você pode usar o Kubernetes para limitar o uso de uma classe de armazenamento específica por namespace usando Cotas de Recursos de Armazenamento, que são por namespace.  Para negar o acesso de um namespace específico a um armazenamento específico, defina a cota de recursos como 0 para essa classe de armazenamento.
