---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-trident.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: A Trident segue um ciclo de lançamentos de quatro meses, lançando três versões principais a cada ano civil.  Cada nova versão se baseia nas versões anteriores, oferecendo novos recursos e melhorias de desempenho, além de correções de bugs e aprimoramentos.  É recomendável que você atualize pelo menos uma vez por ano para aproveitar os novos recursos do Trident. 
---
= Trident aprimorado
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partir da versão 24.02, o Trident segue um ciclo de lançamentos de quatro meses, disponibilizando três versões principais a cada ano civil.  Cada nova versão se baseia nas versões anteriores e oferece novos recursos, melhorias de desempenho, correções de bugs e aprimoramentos.  Recomendamos que você atualize pelo menos uma vez por ano para aproveitar os novos recursos do Trident.



== Considerações antes de atualizar

Ao atualizar para a versão mais recente do Trident, considere o seguinte:

* Deve haver apenas uma instância do Trident instalada em todos os namespaces de um determinado cluster Kubernetes.
* O Trident 23.07 e versões posteriores exigem snapshots de volume v1 e não são mais compatíveis com snapshots alfa ou beta.
* Se você criou o Cloud Volumes Service para o Google Cloud nolink:../trident-use/gcp.html#learn-about-trident-support-for-cloud-volumes-service-for-google-cloud["Tipo de serviço CVS"] Você precisa atualizar a configuração do backend para usar o `standardsw` ou `zoneredundantstandardsw` Nível de serviço ao atualizar do Trident 23.01.  A falha na atualização do `serviceLevel` Problemas no backend podem causar falhas nos volumes. Consulte link:../trident-use/gcp.html#cvs-service-type-examples["Exemplos de tipos de serviço da CVS"] para mais detalhes.
* Ao fazer o upgrade, é importante que você forneça `parameter.fsType` em `StorageClasses` Usado pela Trident.  Você pode excluir e recriar `StorageClasses` sem interromper os volumes preexistentes.
+
** Este é um **requisito** para a aplicação da lei. https://kubernetes.io/docs/tasks/configure-pod-container/security-context/["contextos de segurança"^] para volumes SAN.
** O diretório https://github.com/NetApp/trident/tree/master/trident-installer/sample-input [sample input^] contém exemplos, como https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-basic.yaml.templ[`storage-class-basic.yaml.templ` ^] e link: https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-samples/storage-class-bronze-default.yaml[`storage-class-bronze-default.yaml` ^].
** Para obter mais informações, consultelink:../trident-rn.html["Problemas conhecidos"] .






== Passo 1: Selecione uma versão

As versões do Trident seguem um padrão baseado em datas. `YY.MM` convenção de nomenclatura, onde "AA" são os dois últimos dígitos do ano e "MM" é o mês.  Os lançamentos do Dot seguem um `YY.MM.X` convenção, onde "X" é o nível de patch.  Você selecionará a versão para a qual deseja atualizar com base na versão atual.

* Você pode realizar uma atualização direta para qualquer versão de destino que esteja dentro de um intervalo de quatro versões da sua versão instalada.  Por exemplo, você pode atualizar diretamente da versão 24.06 (ou qualquer versão 24.06 com ponto) para a versão 25.06.
* Se você estiver atualizando de uma versão fora do período de quatro versões, execute uma atualização em várias etapas.  Use as instruções de atualização para olink:../earlier-versions.html["versão anterior"] Você está atualizando para a versão mais recente que se encaixa no período de quatro versões.  Por exemplo, se você estiver executando a versão 23.07 e quiser atualizar para a versão 25.06:
+
.. Primeira atualização da versão 23.07 para a 24.06.
.. Em seguida, atualize da versão 24.06 para a 25.06.





NOTE: Ao atualizar usando o operador Trident no OpenShift Container Platform, você deve atualizar para o Trident 21.01.1 ou posterior.  O operador Trident lançado com a versão 21.01.0 contém um problema conhecido que foi corrigido na versão 21.01.1.  Para obter mais detalhes, consulte o https://github.com/NetApp/trident/issues/517["Detalhes do problema no GitHub"^] .



== Etapa 2: Determine o método de instalação original.

Para determinar qual versão você usou para instalar o Trident originalmente:

. Usar `kubectl get pods -n trident` para examinar as cápsulas.
+
** Se não houver um módulo de operador, o Trident foi instalado usando `tridentctl` .
** Caso exista um pod de operador, o Trident foi instalado usando o operador Trident, seja manualmente ou através do Helm.


. Se houver um módulo de operador, use-o. `kubectl describe torc` Para determinar se o Trident foi instalado usando o Helm.
+
** Se houver uma etiqueta "Helm", o Trident foi instalado usando o Helm.
** Se não houver nenhuma etiqueta "Helm", o Trident foi instalado manualmente usando o operador Trident .






== Etapa 3: Selecione um método de atualização

Geralmente, você deve atualizar usando o mesmo método que usou para a instalação inicial; no entanto, você podelink:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["alternar entre métodos de instalação"] .  Existem duas opções para aprimorar o Trident.

* link:upgrade-operator.html["Faça o upgrade usando o operador Trident ."]
+

TIP: Sugerimos que você reviselink:upgrade-operator-overview.html["Entenda o fluxo de trabalho de atualização do operador."] antes de atualizar com a operadora.

* 

