---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-tridentctl.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: 'Você pode atualizar facilmente uma instalação Trident existente usando `tridentctl` .' 
---
= Atualize com tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Você pode atualizar facilmente uma instalação Trident existente usando `tridentctl` .

.Sobre esta tarefa
Desinstalar e reinstalar o Trident funciona como uma atualização.  Ao desinstalar o Trident, o Persistent Volume Claim (PVC) e o Persistent Volume (PV) usados ​​pela implementação do Trident não são excluídos.  Os PVs que já foram provisionados permanecerão disponíveis enquanto o Trident estiver offline, e o Trident provisionará volumes para quaisquer PVCs que forem criados nesse período, após o seu retorno à internet.

.Antes de começar
Análiselink:upgrade-trident.html#select-an-upgrade-method["Selecione um método de atualização"] antes de atualizar usando `tridentctl` .

.Passos
. Execute o comando de desinstalação em `tridentctl` Remover todos os recursos associados ao Trident, exceto os CRDs e objetos relacionados.
+
[listing]
----
./tridentctl uninstall -n <namespace>
----
. Reinstale o Trident. Consultelink:../trident-get-started/kubernetes-deploy-tridentctl.html["Instale o Trident usando o tridentctl"] .



IMPORTANT: Não interrompa o processo de atualização.  Certifique-se de que o instalador seja executado até a conclusão.
