---
sidebar: sidebar 
permalink: trident-use/backend_ops_tridentctl.html 
keywords: backends, storage system, anf, cvs for aws, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, tridentctl, create backends, delete backends, view backends, update backends 
summary: 'Aprenda como executar operações de gerenciamento de back-end usando `tridentctl` .' 
---
= Realize a gestão de backend com o tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aprenda como executar operações de gerenciamento de back-end usando `tridentctl` .



== Crie um backend

Depois de criar umlink:backends.html["arquivo de configuração do backend"^] Execute o seguinte comando:

[listing]
----
tridentctl create backend -f <backend-file> -n trident
----
Se a criação do backend falhar, algo estava errado com a configuração do backend.  Você pode visualizar os registros para determinar a causa executando o seguinte comando:

[listing]
----
tridentctl logs -n trident
----
Após identificar e corrigir o problema com o arquivo de configuração, você pode simplesmente executar o `create` Comande novamente.



== Excluir um backend

Para excluir um backend do Trident, faça o seguinte:

. Recuperar o nome do backend:
+
[listing]
----
tridentctl get backend -n trident
----
. Exclua o backend:
+
[listing]
----
tridentctl delete backend <backend-name> -n trident
----



NOTE: Se o Trident tiver provisionado volumes e snapshots desse backend que ainda existam, a exclusão do backend impede que novos volumes sejam provisionados por ele.  O sistema de backend continuará existindo em um estado de "Exclusão".



== Veja os backends existentes

Para visualizar os backends que o Trident conhece, faça o seguinte:

* Para obter um resumo, execute o seguinte comando:
+
[listing]
----
tridentctl get backend -n trident
----
* Para obter todos os detalhes, execute o seguinte comando:
+
[listing]
----
tridentctl get backend -o json -n trident
----




== Atualizar um backend

Após criar um novo arquivo de configuração de backend, execute o seguinte comando:

[listing]
----
tridentctl update backend <backend-name> -f <backend-file> -n trident
----
Se a atualização do servidor falhar, algo estava errado com a configuração do servidor ou você tentou uma atualização inválida.  Você pode visualizar os registros para determinar a causa executando o seguinte comando:

[listing]
----
tridentctl logs -n trident
----
Após identificar e corrigir o problema com o arquivo de configuração, você pode simplesmente executar o `update` Comande novamente.



== Identifique as classes de armazenamento que utilizam um backend.

Este é um exemplo do tipo de pergunta que você pode responder com o JSON que `tridentctl` Saídas para objetos de backend.  Isso usa o `jq` utilitário, que você precisa instalar.

[listing]
----
tridentctl get backend -o json | jq '[.items[] | {backend: .name, storageClasses: [.storage[].storageClasses]|unique}]'
----
Isso também se aplica a backends que foram criados usando `TridentBackendConfig` .
