---
sidebar: sidebar 
permalink: trident-use/gcnv-prep.html 
keywords: trident backend, google cloud netapp volumes, smb volumes, active directory, csi proxy, aks, cloud identity 
summary: Antes de configurar o backend do Google Cloud NetApp Volumes , você precisa garantir que os seguintes requisitos sejam atendidos. 
---
= Prepare-se para configurar um backend do Google Cloud NetApp Volumes.
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Antes de configurar o backend do Google Cloud NetApp Volumes , você precisa garantir que os seguintes requisitos sejam atendidos.



== Pré-requisitos para volumes NFS

Se você estiver usando o Google Cloud NetApp Volumes pela primeira vez ou em um novo local, será necessária alguma configuração inicial para configurar o Google Cloud NetApp Volumes e criar um volume NFS. Consultelink:https://cloud.google.com/netapp/volumes/docs/before-you-begin/application-resilience["Antes de começar"^] .

Certifique-se de ter o seguinte antes de configurar o backend do Google Cloud NetApp Volumes :

* Uma conta do Google Cloud configurada com o serviço Google Cloud NetApp Volumes . Consultelink:https://cloud.google.com/netapp-volumes["Google Cloud NetApp Volumes"^] .
* Número do projeto da sua conta do Google Cloud. Consultelink:https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects["Identificação de projetos"^] .
* Uma conta de serviço do Google Cloud com o administrador de volumes da NetApp.(`roles/netapp.admin` ) papel. Consultelink:https://cloud.google.com/netapp/volumes/docs/get-started/configure-access/iam#roles_and_permissions["Funções e permissões de Gestão de Identidade e Acesso"^] .
* Arquivo de chave API para sua conta GCNV.  Consultelink:https://cloud.google.com/iam/docs/keys-create-delete#creating["Criar uma chave de conta de serviço"^]
* Uma piscina de armazenamento. Consultelink:https://cloud.google.com/netapp/volumes/docs/configure-and-use/storage-pools/overview["Visão geral dos pools de armazenamento"^] .


Para obter mais informações sobre como configurar o acesso aos Google Cloud NetApp Volumes, consulte:link:https://cloud.google.com/netapp/volumes/docs/get-started/configure-access/workflow#before_you_begin["Configure o acesso aos Google Cloud NetApp Volumes."^] .
