---
sidebar: sidebar 
permalink: trident-use/gcp.html 
keywords: trident backend, cloud volumes service for google cloud platform, google cloud platform, gcp, storage pool labels, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Aprenda como configurar o Cloud Volumes Service para Google Cloud como backend da sua instalaĂ§ĂŁo do Trident usando as configuraĂ§Ă”es de exemplo fornecidas. 
---
= Configure um Cloud Volumes Service para o backend do Google Cloud.
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aprenda como configurar o NetApp Cloud Volumes Service para Google Cloud como backend para sua instalaĂ§ĂŁo do Trident usando as configuraĂ§Ă”es de exemplo fornecidas.



== Detalhes do driver do Google Cloud

A Trident fornece o `gcp-cvs` O driver deve se comunicar com o cluster.  Os modos de acesso suportados sĂŁo: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="1, 1, 1, 2, 2"]
|===
| Motorista | Protocolo | modo de volume | Modos de acesso suportados | Sistemas de arquivos suportados 


| `gcp-cvs`  a| 
NFS
 a| 
Sistema de arquivos
 a| 
RWO, ROX, RWX, RWOP
 a| 
`nfs`

|===


== Saiba mais sobre o suporte do Trident para o Cloud Volumes Service do Google Cloud.

O Trident pode criar volumes do Cloud Volumes Service de duas maneiras diferentes.link:https://cloud.google.com/architecture/partners/netapp-cloud-volumes/service-types["tipos de serviĂ§o"^] :

* *CVS-Performance*: O tipo de serviĂ§o Trident padrĂŁo.  Este tipo de serviĂ§o otimizado para desempenho Ă© mais adequado para cargas de trabalho de produĂ§ĂŁo que valorizam o desempenho.  O tipo de serviĂ§o CVS-Performance Ă© uma opĂ§ĂŁo de hardware que suporta volumes com tamanho mĂ­nimo de 100 GiB.  VocĂȘ pode escolher um dos seguintes:link:https://cloud.google.com/architecture/partners/netapp-cloud-volumes/service-levels#service_levels_for_the_cvs-performance_service_type["trĂȘs nĂ­veis de serviĂ§o"^] :
+
** `standard`
** `premium`
** `extreme`


* *CVS*: O tipo de serviĂ§o CVS oferece alta disponibilidade zonal com nĂ­veis de desempenho limitados a moderados.  O tipo de serviĂ§o CVS Ă© uma opĂ§ĂŁo de software que utiliza pools de armazenamento para suportar volumes tĂŁo pequenos quanto 1 GiB.  O pool de armazenamento pode conter atĂ© 50 volumes, onde todos os volumes compartilham a capacidade e o desempenho do pool.  VocĂȘ pode escolher um dos seguintes:link:https://cloud.google.com/architecture/partners/netapp-cloud-volumes/service-levels#service_levels_for_the_cvs_service_type["dois nĂ­veis de serviĂ§o"^] :
+
** `standardsw`
** `zoneredundantstandardsw`




.O que vocĂȘ vai precisar
Para configurar e usar o https://cloud.netapp.com/cloud-volumes-service-for-gcp?utm_source=NetAppTrident_ReadTheDocs&utm_campaign=Trident["Cloud Volumes Service para Google Cloud"^] Para o backend, vocĂȘ precisa do seguinte:

* Uma conta do Google Cloud configurada com o serviĂ§o NetApp Cloud Volumes Service.
* NĂșmero do projeto da sua conta do Google Cloud
* conta de serviĂ§o do Google Cloud com o `netappcloudvolumes.admin` papel
* Arquivo de chave de API para sua conta do Cloud Volumes Service .




== OpĂ§Ă”es de configuraĂ§ĂŁo do backend

Cada backend provisiona volumes em uma Ășnica regiĂŁo do Google Cloud.  Para criar volumes em outras regiĂ”es, vocĂȘ pode definir backends adicionais.

[cols="1, 2, 1"]
|===
| ParĂąmetro | DescriĂ§ĂŁo | PadrĂŁo 


| `version` |  | Sempre 1 


| `storageDriverName` | Nome do driver de armazenamento | "gcp-cvs" 


| `backendName` | Nome personalizado ou o backend de armazenamento | Nome do driver + "_" + parte da chave da API 


| `storageClass` | ParĂąmetro opcional usado para especificar o tipo de serviĂ§o CVS.  Usar `software` Para selecionar o tipo de serviĂ§o CVS.  Caso contrĂĄrio, o Trident assume o tipo de serviĂ§o CVS-Performance.(`hardware` ). |  


| `storagePools` | Somente o tipo de serviĂ§o CVS.  ParĂąmetro opcional usado para especificar os conjuntos de armazenamento para a criaĂ§ĂŁo de volumes. |  


| `projectNumber` | NĂșmero do projeto da conta do Google Cloud.  O valor pode ser encontrado na pĂĄgina inicial do portal do Google Cloud. |  


| `hostProjectNumber` | ObrigatĂłrio se estiver usando uma rede VPC compartilhada.  Neste cenĂĄrio, `projectNumber` Ă© o projeto de serviĂ§o, e `hostProjectNumber` Ă© o projeto anfitriĂŁo. |  


| `apiRegion` | A regiĂŁo do Google Cloud onde o Trident cria volumes do Cloud Volumes Service .  Ao criar clusters Kubernetes entre regiĂ”es, os volumes criados em uma regiĂŁo sĂŁo mantidos. `apiRegion` Pode ser usado em cargas de trabalho agendadas em nĂłs em vĂĄrias regiĂ”es do Google Cloud.  O trĂĄfego entre regiĂ”es diferentes acarreta um custo adicional. |  


| `apiKey` | Chave de API para a conta de serviĂ§o do Google Cloud com o `netappcloudvolumes.admin` papel.  Inclui o conteĂșdo formatado em JSON do arquivo de chave privada de uma conta de serviĂ§o do Google Cloud (copiado integralmente para o arquivo de configuraĂ§ĂŁo do backend). |  


| `proxyURL` | URL do proxy, caso seja necessĂĄrio um servidor proxy para conectar-se Ă  conta CVS.  O servidor proxy pode ser um proxy HTTP ou um proxy HTTPS.  Para um proxy HTTPS, a validaĂ§ĂŁo do certificado Ă© ignorada para permitir o uso de certificados autoassinados no servidor proxy.  Servidores proxy com autenticaĂ§ĂŁo ativada nĂŁo sĂŁo suportados. |  


| `nfsMountOptions` | Controle preciso das opĂ§Ă”es de montagem NFS. | "nfsvers=3" 


| `limitVolumeSize` | O provisionamento falharĂĄ se o tamanho do volume solicitado for superior a esse valor. | "" (nĂŁo aplicado por padrĂŁo) 


| `serviceLevel` | O nĂ­vel de desempenho ou serviĂ§o CVS para novos volumes.  Os valores de desempenho do CVS sĂŁo `standard` , `premium` , ou `extreme` .  Os valores CVS sĂŁo `standardsw` ou `zoneredundantstandardsw` . | A configuraĂ§ĂŁo padrĂŁo do CVS-Performance Ă© "standard".  O padrĂŁo do CVS Ă© "standardsw". 


| `network` | A rede do Google Cloud Ă© usada para os volumes do Cloud Volumes Service . | "padrĂŁo" 


| `debugTraceFlags` | Sinalizadores de depuraĂ§ĂŁo a serem usados na resoluĂ§ĂŁo de problemas.  Exemplo, `\{"api":false, "method":true}` .  NĂŁo utilize esta opĂ§ĂŁo a menos que esteja solucionando problemas e precise de um despejo de logs detalhado. | nulo 


| `allowedTopologies` | Para habilitar o acesso entre regiĂ”es, sua definiĂ§ĂŁo de StorageClass para `allowedTopologies` Deve incluir todas as regiĂ”es. Por exemplo:
`- key: topology.kubernetes.io/region
  values:
  - us-east1
  - europe-west1` |  
|===


== OpĂ§Ă”es de provisionamento de volume

VocĂȘ pode controlar o provisionamento de volume padrĂŁo em `defaults` seĂ§ĂŁo do arquivo de configuraĂ§ĂŁo.

[cols=",,"]
|===
| ParĂąmetro | DescriĂ§ĂŁo | PadrĂŁo 


| `exportRule` | Regras de exportaĂ§ĂŁo para novos volumes.  Deve ser uma lista separada por vĂ­rgulas de qualquer combinaĂ§ĂŁo de endereĂ§os IPv4 ou sub-redes IPv4 na notaĂ§ĂŁo CIDR. | "0.0.0.0/0" 


| `snapshotDir` | Acesso ao `.snapshot` diretĂłrio | "falso" 


| `snapshotReserve` | Percentagem do volume reservada para instantĂąneos | "" (aceitar o valor padrĂŁo CVS de 0) 


| `size` | O tamanho dos novos volumes.  O requisito mĂ­nimo de desempenho do CVS Ă© de 100 GiB.  O tamanho mĂ­nimo exigido pelo CVS Ă© 1 GiB. | O tipo de serviĂ§o CVS-Performance tem como padrĂŁo "100GiB".  O tipo de serviĂ§o CVS nĂŁo define um valor padrĂŁo, mas requer um mĂ­nimo de 1 GiB. 
|===


== Exemplos de tipos de serviĂ§o CVS-Performance

Os exemplos a seguir fornecem configuraĂ§Ă”es de amostra para o tipo de serviĂ§o CVS-Performance.

.Exemplo 1: ConfiguraĂ§ĂŁo mĂ­nima
[%collapsible]
====
Esta Ă© a configuraĂ§ĂŁo mĂ­nima de backend usando o tipo de serviĂ§o CVS-Performance padrĂŁo com o nĂ­vel de serviĂ§o "standard" padrĂŁo.

[source, yaml]
----
---
version: 1
storageDriverName: gcp-cvs
projectNumber: "012345678901"
apiRegion: us-west2
apiKey:
  type: service_account
  project_id: my-gcp-project
  private_key_id: <id_value>
  private_key: |
    -----BEGIN PRIVATE KEY-----
    <key_value>
    -----END PRIVATE KEY-----
  client_email: cloudvolumes-admin-sa@my-gcp-project.iam.gserviceaccount.com
  client_id: "123456789012345678901"
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/cloudvolumes-admin-sa%40my-gcp-project.iam.gserviceaccount.com
----
====
.Exemplo 2: ConfiguraĂ§ĂŁo do nĂ­vel de serviĂ§o
[%collapsible]
====
Este exemplo ilustra as opĂ§Ă”es de configuraĂ§ĂŁo do backend, incluindo o nĂ­vel de serviĂ§o e os valores padrĂŁo de volume.

[source, yaml]
----
---
version: 1
storageDriverName: gcp-cvs
projectNumber: '012345678901'
apiRegion: us-west2
apiKey:
  type: service_account
  project_id: my-gcp-project
  private_key_id: "<id_value>"
  private_key: |
    -----BEGIN PRIVATE KEY-----
    <key_value>
    -----END PRIVATE KEY-----
  client_email: cloudvolumes-admin-sa@my-gcp-project.iam.gserviceaccount.com
  client_id: '123456789012345678901'
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/cloudvolumes-admin-sa%40my-gcp-project.iam.gserviceaccount.com
proxyURL: http://proxy-server-hostname/
nfsMountOptions: vers=3,proto=tcp,timeo=600
limitVolumeSize: 10Ti
serviceLevel: premium
defaults:
  snapshotDir: 'true'
  snapshotReserve: '5'
  exportRule: 10.0.0.0/24,10.0.1.0/24,10.0.2.100
  size: 5Ti
----
====
.Exemplo 3: ConfiguraĂ§ĂŁo de pool virtual
[%collapsible]
====
Este exemplo usa `storage` para configurar pools virtuais e o `StorageClasses` que se referem a eles.  Consulte<<DefiniĂ§Ă”es de classe de armazenamento>> para ver como as classes de armazenamento foram definidas.

Aqui, sĂŁo definidos valores padrĂŁo especĂ­ficos para todos os pools virtuais, que definem o `snapshotReserve` a 5% e o `exportRule` para 0.0.0.0/0.  Os pools virtuais sĂŁo definidos em `storage` seĂ§ĂŁo.  Cada piscina virtual individual define a sua prĂłpria. `serviceLevel` E algumas pools sobrescrevem os valores padrĂŁo.  RĂłtulos de piscinas virtuais foram usados para diferenciar as piscinas com base em `performance` e `protection` .

[source, yaml]
----
---
version: 1
storageDriverName: gcp-cvs
projectNumber: '012345678901'
apiRegion: us-west2
apiKey:
  type: service_account
  project_id: my-gcp-project
  private_key_id: "<id_value>"
  private_key: |
    -----BEGIN PRIVATE KEY-----
    <key_value>
    -----END PRIVATE KEY-----
  client_email: cloudvolumes-admin-sa@my-gcp-project.iam.gserviceaccount.com
  client_id: '123456789012345678901'
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/cloudvolumes-admin-sa%40my-gcp-project.iam.gserviceaccount.com
nfsMountOptions: vers=3,proto=tcp,timeo=600
defaults:
  snapshotReserve: '5'
  exportRule: 0.0.0.0/0
labels:
  cloud: gcp
region: us-west2
storage:
- labels:
    performance: extreme
    protection: extra
  serviceLevel: extreme
  defaults:
    snapshotDir: 'true'
    snapshotReserve: '10'
    exportRule: 10.0.0.0/24
- labels:
    performance: extreme
    protection: standard
  serviceLevel: extreme
- labels:
    performance: premium
    protection: extra
  serviceLevel: premium
  defaults:
    snapshotDir: 'true'
    snapshotReserve: '10'
- labels:
    performance: premium
    protection: standard
  serviceLevel: premium
- labels:
    performance: standard
  serviceLevel: standard

----
====


=== DefiniĂ§Ă”es de classe de armazenamento

As seguintes definiĂ§Ă”es de StorageClass aplicam-se ao exemplo de configuraĂ§ĂŁo de pool virtual.  Usando `parameters.selector` VocĂȘ pode especificar para cada StorageClass o pool virtual usado para hospedar um volume.  O volume terĂĄ os aspectos definidos na piscina escolhida.

.Exemplo de classe de armazenamento
[%collapsible]
====
[source, yaml]
----
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvs-extreme-extra-protection
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=extreme; protection=extra
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvs-extreme-standard-protection
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=premium; protection=standard
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvs-premium-extra-protection
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=premium; protection=extra
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvs-premium
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=premium; protection=standard
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvs-standard
provisioner: csi.trident.netapp.io
parameters:
  selector: performance=standard
allowVolumeExpansion: true
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cvs-extra-protection
provisioner: csi.trident.netapp.io
parameters:
  selector: protection=extra
allowVolumeExpansion: true

----
====
* A primeira StorageClass(`cvs-extreme-extra-protection` ) mapeia para a primeira piscina virtual.  Esta Ă© a Ășnica piscina que oferece desempenho extremo com uma reserva instantĂąnea de 10%.
* A Ășltima StorageClass(`cvs-extra-protection` ) menciona qualquer pool de armazenamento que forneĂ§a uma reserva de snapshot de 10%.  O Trident decide qual pool virtual serĂĄ selecionado e garante que o requisito de reserva de snapshots seja atendido.




== Exemplos de tipos de serviĂ§o CVS

Os exemplos a seguir fornecem configuraĂ§Ă”es de amostra para o tipo de serviĂ§o CVS.

.Exemplo 1: ConfiguraĂ§ĂŁo mĂ­nima
[%collapsible]
====
Esta Ă© a configuraĂ§ĂŁo mĂ­nima de backend usando `storageClass` para especificar o tipo de serviĂ§o CVS e o padrĂŁo `standardsw` nĂ­vel de serviĂ§o.

[source, yaml]
----
---
version: 1
storageDriverName: gcp-cvs
projectNumber: '012345678901'
storageClass: software
apiRegion: us-east4
apiKey:
  type: service_account
  project_id: my-gcp-project
  private_key_id: "<id_value>"
  private_key: |
    -----BEGIN PRIVATE KEY-----
    <key_value>
    -----END PRIVATE KEY-----
  client_email: cloudvolumes-admin-sa@my-gcp-project.iam.gserviceaccount.com
  client_id: '123456789012345678901'
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/cloudvolumes-admin-sa%40my-gcp-project.iam.gserviceaccount.com
serviceLevel: standardsw
----
====
.Exemplo 2: ConfiguraĂ§ĂŁo do pool de armazenamento
[%collapsible]
====
Esta configuraĂ§ĂŁo de backend de exemplo usa `storagePools` Para configurar um pool de armazenamento.

[source, yaml]
----
---
version: 1
storageDriverName: gcp-cvs
backendName: gcp-std-so-with-pool
projectNumber: '531265380079'
apiRegion: europe-west1
apiKey:
  type: service_account
  project_id: cloud-native-data
  private_key_id: "<id_value>"
  private_key: |-
    -----BEGIN PRIVATE KEY-----
    <key_value>
    -----END PRIVATE KEY-----
  client_email: cloudvolumes-admin-sa@cloud-native-data.iam.gserviceaccount.com
  client_id: '107071413297115343396'
  auth_uri: https://accounts.google.com/o/oauth2/auth
  token_uri: https://oauth2.googleapis.com/token
  auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
  client_x509_cert_url: https://www.googleapis.com/robot/v1/metadata/x509/cloudvolumes-admin-sa%40cloud-native-data.iam.gserviceaccount.com
storageClass: software
zone: europe-west1-b
network: default
storagePools:
- 1bc7f380-3314-6005-45e9-c7dc8c2d7509
serviceLevel: Standardsw

----
====


== O que vem a seguir?

ApĂłs criar o arquivo de configuraĂ§ĂŁo do backend, execute o seguinte comando:

[listing]
----
tridentctl create backend -f <backend-file>
----
Se a criaĂ§ĂŁo do backend falhar, hĂĄ algo errado com a configuraĂ§ĂŁo do backend.  VocĂȘ pode visualizar os registros para determinar a causa executando o seguinte comando:

[listing]
----
tridentctl logs
----
ApĂłs identificar e corrigir o problema com o arquivo de configuraĂ§ĂŁo, vocĂȘ poderĂĄ executar o comando de criaĂ§ĂŁo novamente.
