---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Aprenda a configurar um backend ONTAP com drivers ONTAP SAN. 
---
= Visão geral do driver ONTAP SAN
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aprenda a configurar um backend ONTAP com os drivers ONTAP SAN do Cloud Volumes ONTAP .



== Detalhes do driver ONTAP SAN

A Trident fornece os seguintes drivers de armazenamento SAN para comunicação com o cluster ONTAP .  Os modos de acesso suportados são: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Motorista | Protocolo | modo de volume | Modos de acesso suportados | Sistemas de arquivos suportados 


| `ontap-san`  a| 
iSCSI SCSI sobre FC
 a| 
Bloquear
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sem sistema de arquivos; dispositivo de bloco bruto



| `ontap-san`  a| 
iSCSI SCSI sobre FC
 a| 
Sistema de arquivos
 a| 
RWO, RWOP

ROX e RWX não estão disponíveis no modo de volume do sistema de arquivos.
 a| 
`xfs`, `ext3` , `ext4`



| `ontap-san`  a| 
NVMe/TCP

Consulte<<Considerações adicionais para NVMe/TCP>> .
 a| 
Bloquear
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sem sistema de arquivos; dispositivo de bloco bruto



| `ontap-san`  a| 
NVMe/TCP

Consulte<<Considerações adicionais para NVMe/TCP>> .
 a| 
Sistema de arquivos
 a| 
RWO, RWOP

ROX e RWX não estão disponíveis no modo de volume do sistema de arquivos.
 a| 
`xfs`, `ext3` , `ext4`



| `ontap-san-economy`  a| 
iSCSI
 a| 
Bloquear
 a| 
RWO, ROX, RWX, RWOP
 a| 
Sem sistema de arquivos; dispositivo de bloco bruto



| `ontap-san-economy`  a| 
iSCSI
 a| 
Sistema de arquivos
 a| 
RWO, RWOP

ROX e RWX não estão disponíveis no modo de volume do sistema de arquivos.
 a| 
`xfs`, `ext3` , `ext4`

|===
[WARNING]
====
* Usar `ontap-san-economy` somente se a contagem de uso de volume persistente prevista for maior quelink:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limites de volume ONTAP suportados"^] .
* Usar `ontap-nas-economy` somente se a contagem de uso de volume persistente prevista for maior quelink:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limites de volume ONTAP suportados"^] e o `ontap-san-economy` O driver não pode ser usado.
* Não use `ontap-nas-economy` Se você prevê a necessidade de proteção de dados, recuperação de desastres ou mobilidade.
* A NetApp não recomenda o uso do Flexvol autogrow em todos os drivers ONTAP , exceto no ontap-san.  Como solução alternativa, o Trident suporta o uso de reserva de snapshots e dimensiona os volumes Flexvol de acordo.


====


== Permissões do usuário

O Trident espera ser executado como administrador ONTAP ou SVM, normalmente usando o `admin` usuário do cluster ou um `vsadmin` Usuário SVM, ou um usuário com um nome diferente que tenha a mesma função.  Para implementações do Amazon FSx for NetApp ONTAP , o Trident espera ser executado como administrador do ONTAP ou do SVM, usando o cluster. `fsxadmin` usuário ou um `vsadmin` Usuário SVM, ou um usuário com um nome diferente que tenha a mesma função.  O `fsxadmin` O usuário é um substituto limitado para o usuário administrador do cluster.


NOTE: Se você usar o `limitAggregateUsage` Para configurar o parâmetro, são necessárias permissões de administrador do cluster.  Ao usar o Amazon FSx for NetApp ONTAP com Trident, o `limitAggregateUsage` O parâmetro não funcionará com o `vsadmin` e `fsxadmin` contas de usuário.  A operação de configuração falhará se você especificar este parâmetro.

Embora seja possível criar uma função mais restritiva dentro do ONTAP que um driver Trident possa usar, não recomendamos isso.  A maioria das novas versões do Trident chamará APIs adicionais que precisarão ser consideradas, tornando as atualizações difíceis e propensas a erros.



== Considerações adicionais para NVMe/TCP

O Trident suporta o protocolo de memória não volátil expressa (NVMe) usando o `ontap-san` motorista incluindo:

* IPv6
* Instantâneos e clones de volumes NVMe
* Redimensionar um volume NVMe
* Importar um volume NVMe criado fora do Trident para que seu ciclo de vida possa ser gerenciado pelo Trident.
* Multicaminhamento nativo NVMe
* Encerramento correto ou incorreto dos nós K8s (24.06)


O Trident não suporta:

* DH-HMAC-CHAP que é suportado nativamente por NVMe
* Mapeamento de dispositivos (DM) com múltiplos caminhos
* Criptografia LUKS



NOTE: O NVMe é compatível apenas com APIs REST ONTAP e não com ONTAPI (ZAPI).
