---
sidebar: sidebar 
permalink: trident-use/ontap-nas.html 
keywords: trident backend, ontap nas, ontap-nas, ontap-nas-economy, ontap-nas-flexgroups, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: Aprenda a configurar um backend ONTAP com drivers ONTAP NAS. 
---
= Visão geral do driver ONTAP NAS
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Aprenda a configurar um backend ONTAP com os drivers ONTAP NAS do ONTAP e do Cloud Volumes ONTAP .



== Detalhes do driver ONTAP NAS

A Trident fornece os seguintes drivers de armazenamento NAS para comunicação com o cluster ONTAP .  Os modos de acesso suportados são: _ReadWriteOnce_ (RWO), _ReadOnlyMany_ (ROX), _ReadWriteMany_ (RWX), _ReadWriteOncePod_ (RWOP).

[cols="2, 1, 1, 2, 2"]
|===
| Motorista | Protocolo | modo de volume | Modos de acesso suportados | Sistemas de arquivos suportados 


| `ontap-nas`  a| 
NFS SMB
 a| 
Sistema de arquivos
 a| 
RWO, ROX, RWX, RWOP
 a| 
"," `nfs` , `smb`



| `ontap-nas-economy`  a| 
NFS SMB
 a| 
Sistema de arquivos
 a| 
RWO, ROX, RWX, RWOP
 a| 
"," `nfs` , `smb`



| `ontap-nas-flexgroup`  a| 
NFS SMB
 a| 
Sistema de arquivos
 a| 
RWO, ROX, RWX, RWOP
 a| 
"," `nfs` , `smb`

|===
[WARNING]
====
* Usar `ontap-san-economy` somente se a contagem de uso de volume persistente prevista for maior quelink:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limites de volume ONTAP suportados"^] .
* Usar `ontap-nas-economy` somente se a contagem de uso de volume persistente prevista for maior quelink:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["limites de volume ONTAP suportados"^] e o `ontap-san-economy` O driver não pode ser usado.
* Não use `ontap-nas-economy` Se você prevê a necessidade de proteção de dados, recuperação de desastres ou mobilidade.
* A NetApp não recomenda o uso do Flexvol autogrow em todos os drivers ONTAP , exceto no ontap-san.  Como solução alternativa, o Trident suporta o uso de reserva de snapshots e dimensiona os volumes Flexvol de acordo.


====


== Permissões do usuário

O Trident espera ser executado como administrador ONTAP ou SVM, normalmente usando o `admin` usuário do cluster ou um `vsadmin` Usuário SVM, ou um usuário com um nome diferente que tenha a mesma função.

Para implementações do Amazon FSx for NetApp ONTAP , o Trident espera ser executado como administrador do ONTAP ou do SVM, usando o cluster. `fsxadmin` usuário ou um `vsadmin` Usuário SVM, ou um usuário com um nome diferente que tenha a mesma função.  O `fsxadmin` O usuário é um substituto limitado para o usuário administrador do cluster.


NOTE: Se você usar o `limitAggregateUsage` Para configurar o parâmetro, são necessárias permissões de administrador do cluster.  Ao usar o Amazon FSx for NetApp ONTAP com Trident, o `limitAggregateUsage` O parâmetro não funcionará com o `vsadmin` e `fsxadmin` contas de usuário.  A operação de configuração falhará se você especificar este parâmetro.

Embora seja possível criar uma função mais restritiva dentro do ONTAP que um driver Trident possa usar, não recomendamos isso.  A maioria das novas versões do Trident chamará APIs adicionais que precisarão ser consideradas, tornando as atualizações difíceis e propensas a erros.
