---
sidebar: sidebar 
permalink: trident-use/ontap-san-prep.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fcp, asa r2, iscsi, nvme/tcp 
summary: Saiba como se preparar para configurar um backend ONTAP com drivers ONTAP SAN. 
---
= Prepare-se para configurar o backend com os drivers ONTAP SAN.
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Compreenda os requisitos e as opções de autenticação para configurar um backend ONTAP com drivers ONTAP SAN.



== Requisitos

Para todos os backends ONTAP , o Trident exige que pelo menos um agregado seja atribuído à SVM.


NOTE: link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["Sistemas ASA r2"^]diferem de outros sistemas ONTAP (ASA, AFF e FAS) na implementação de sua camada de armazenamento.  Nos sistemas ASA r2, as zonas de disponibilidade de armazenamento são usadas em vez de agregados.  Consultelink:https://kb.netapp.com/on-prem/ASAr2/ASAr2_KBs/su_create_by_SVM_admin_using_CLI_fails_with_error_No_candidate_aggregates_are_available_for_storage_services["esse"^] Artigo da Base de Conhecimento sobre como atribuir agregados a SVMs em sistemas ASA r2.

Lembre-se de que você também pode executar mais de um driver e criar classes de armazenamento que apontem para um ou outro.  Por exemplo, você poderia configurar um `san-dev` classe que usa o `ontap-san` motorista e um `san-default` classe que usa o `ontap-san-economy` um.

Todos os seus nós de trabalho do Kubernetes devem ter as ferramentas iSCSI apropriadas instaladas. Consulte link:worker-node-prep.html["Prepare o nó de trabalho"] para mais detalhes.



== Autenticar o backend ONTAP

O Trident oferece dois modos de autenticação de um backend ONTAP .

* Com base em credenciais: o nome de usuário e a senha de um usuário do ONTAP com as permissões necessárias.  Recomenda-se o uso de uma função de login de segurança predefinida, como `admin` ou `vsadmin` Para garantir a máxima compatibilidade com as versões do ONTAP .
* Com base em certificado: o Trident também pode se comunicar com um cluster ONTAP usando um certificado instalado no backend.  Aqui, a definição do backend deve conter os valores codificados em Base64 do certificado do cliente, da chave e do certificado da CA confiável, se utilizado (recomendado).


Você pode atualizar os sistemas de backend existentes para alternar entre métodos baseados em credenciais e métodos baseados em certificados.  No entanto, apenas um método de autenticação é suportado por vez.  Para mudar para um método de autenticação diferente, você deve remover o método existente da configuração do backend.


WARNING: Se você tentar fornecer *tanto credenciais quanto certificados*, a criação do backend falhará com um erro informando que mais de um método de autenticação foi fornecido no arquivo de configuração.



=== Ativar autenticação baseada em credenciais

O Trident requer as credenciais de um administrador com escopo de SVM/cluster para se comunicar com o backend do ONTAP .  Recomenda-se o uso de funções padrão predefinidas, como: `admin` ou `vsadmin` .  Isso garante a compatibilidade futura com versões futuras do ONTAP que possam expor APIs de recursos a serem usadas por versões futuras do Trident .  É possível criar e usar uma função de login de segurança personalizada com o Trident, mas isso não é recomendado.

Uma definição de backend de exemplo terá a seguinte aparência:

[role="tabbed-block"]
====
.YAML
--
[source, yaml]
----
---
version: 1
backendName: ExampleBackend
storageDriverName: ontap-san
managementLIF: 10.0.0.1
svm: svm_nfs
username: vsadmin
password: password
----
--
.JSON
--
[source, json]
----
{
  "version": 1,
  "backendName": "ExampleBackend",
  "storageDriverName": "ontap-san",
  "managementLIF": "10.0.0.1",
  "svm": "svm_nfs",
  "username": "vsadmin",
  "password": "password"
}

----
--
====
Lembre-se de que a definição do backend é o único lugar onde as credenciais são armazenadas em texto simples.  Após a criação do backend, os nomes de usuário/senhas são codificados em Base64 e armazenados como segredos do Kubernetes.  A criação ou atualização de um backend é a única etapa que exige conhecimento das credenciais.  Sendo assim, trata-se de uma operação exclusiva para administradores, a ser realizada pelo administrador do Kubernetes/armazenamento.



=== Habilitar autenticação baseada em certificado

Novos e existentes sistemas de backend podem usar um certificado e se comunicar com o backend ONTAP .  São necessários três parâmetros na definição do backend.

* clientCertificate: Valor do certificado do cliente codificado em Base64.
* clientPrivateKey: Valor codificado em Base64 da chave privada associada.
* trustedCACertificate: Valor codificado em Base64 do certificado da Autoridade Certificadora (CA) confiável.  Caso esteja utilizando uma Autoridade Certificadora (CA) confiável, este parâmetro deve ser fornecido.  Isso pode ser ignorado se nenhuma Autoridade Certificadora (CA) confiável for utilizada.


Um fluxo de trabalho típico envolve as seguintes etapas.

.Passos
. Gere um certificado e uma chave de cliente.  Ao gerar o código, defina o Nome Comum (CN) para o usuário ONTAP que será usado para autenticação.
+
[listing]
----
openssl req -x509 -nodes -days 1095 -newkey rsa:2048 -keyout k8senv.key -out k8senv.pem -subj "/C=US/ST=NC/L=RTP/O=NetApp/CN=admin"
----
. Adicione um certificado CA confiável ao cluster ONTAP .  Isso pode já estar sendo tratado pelo administrador de armazenamento.  Ignore se nenhuma Autoridade Certificadora (CA) confiável for utilizada.
+
[listing]
----
security certificate install -type server -cert-name <trusted-ca-cert-name> -vserver <vserver-name>
ssl modify -vserver <vserver-name> -server-enabled true -client-enabled true -common-name <common-name> -serial <SN-from-trusted-CA-cert> -ca <cert-authority>
----
. Instale o certificado e a chave do cliente (do passo 1) no cluster ONTAP .
+
[listing]
----
security certificate install -type client-ca -cert-name <certificate-name> -vserver <vserver-name>
security ssl modify -vserver <vserver-name> -client-enabled true
----
+

NOTE: Após executar este comando, ONTAP solicitará a entrada do certificado. Cole o conteúdo do  `k8senv.pem` arquivo gerado na etapa 1, depois insira  `END` para concluir a instalação.

. Confirme se a função de login de segurança do ONTAP é compatível. `cert` método de autenticação.
+
[listing]
----
security login create -user-or-group-name admin -application ontapi -authentication-method cert
security login create -user-or-group-name admin -application http -authentication-method cert
----
. Teste a autenticação usando o certificado gerado.  Substitua < ONTAP Management LIF> e <vserver name> pelo endereço IP do Management LIF e pelo nome do SVM.
+
[listing]
----
curl -X POST -Lk https://<ONTAP-Management-LIF>/servlets/netapp.servlets.admin.XMLrequest_filer --key k8senv.key --cert ~/k8senv.pem -d '<?xml version="1.0" encoding="UTF-8"?><netapp xmlns="http://www.netapp.com/filer/admin" version="1.21" vfiler="<vserver-name>"><vserver-get></vserver-get></netapp>'
----
. Codifique o certificado, a chave e o certificado da CA confiável em Base64.
+
[listing]
----
base64 -w 0 k8senv.pem >> cert_base64
base64 -w 0 k8senv.key >> key_base64
base64 -w 0 trustedca.pem >> trustedca_base64
----
. Crie o backend usando os valores obtidos na etapa anterior.
+
[listing]
----
cat cert-backend.json
{
"version": 1,
"storageDriverName": "ontap-san",
"backendName": "SanBackend",
"managementLIF": "1.2.3.4",
"svm": "vserver_test",
"clientCertificate": "Faaaakkkkeeee...Vaaalllluuuueeee",
"clientPrivateKey": "LS0tFaKE...0VaLuES0tLS0K",
"trustedCACertificate": "QNFinfO...SiqOyN",
"storagePrefix": "myPrefix_"
}

tridentctl create backend -f cert-backend.json -n trident
+------------+----------------+--------------------------------------+--------+---------+
|    NAME    | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+------------+----------------+--------------------------------------+--------+---------+
| SanBackend | ontap-san      | 586b1cd5-8cf8-428d-a76c-2872713612c1 | online |       0 |
+------------+----------------+--------------------------------------+--------+---------+
----




=== Atualize os métodos de autenticação ou altere as credenciais.

Você pode atualizar um backend existente para usar um método de autenticação diferente ou para rotacionar suas credenciais.  Isso funciona nos dois sentidos: os sistemas internos que utilizam nome de usuário/senha podem ser atualizados para usar certificados; os sistemas internos que utilizam certificados podem ser atualizados para usar nome de usuário/senha.  Para fazer isso, você deve remover o método de autenticação existente e adicionar o novo método de autenticação.  Em seguida, utilize o arquivo backend.json atualizado, que contém os parâmetros necessários, para executar o comando. `tridentctl backend update` .

[listing]
----
cat cert-backend-updated.json
{
"version": 1,
"storageDriverName": "ontap-san",
"backendName": "SanBackend",
"managementLIF": "1.2.3.4",
"svm": "vserver_test",
"username": "vsadmin",
"password": "password",
"storagePrefix": "myPrefix_"
}

#Update backend with tridentctl
tridentctl update backend SanBackend -f cert-backend-updated.json -n trident
+------------+----------------+--------------------------------------+--------+---------+
|    NAME    | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+------------+----------------+--------------------------------------+--------+---------+
| SanBackend | ontap-san      | 586b1cd5-8cf8-428d-a76c-2872713612c1 | online |       9 |
+------------+----------------+--------------------------------------+--------+---------+
----

NOTE: Ao rotacionar senhas, o administrador de armazenamento deve primeiro atualizar a senha do usuário no ONTAP.  Em seguida, é realizada uma atualização do sistema interno.  Ao rotacionar certificados, vários certificados podem ser adicionados ao usuário.  Em seguida, o sistema de backend é atualizado para usar o novo certificado, após o que o certificado antigo pode ser excluído do cluster ONTAP .

A atualização de um backend não interrompe o acesso a volumes já criados, nem afeta as conexões de volume feitas posteriormente.  Uma atualização bem-sucedida do backend indica que o Trident pode se comunicar com o backend ONTAP e lidar com futuras operações em grande volume.



=== Criar função ONTAP personalizada para Trident

Você pode criar uma função de cluster ONTAP com privilégios mínimos para que não precise usar a função de administrador do ONTAP para executar operações no Trident.  Ao incluir o nome de usuário em uma configuração de backend do Trident , o Trident usa a função de cluster ONTAP que você criou para executar as operações.

Consultelink:https://github.com/NetApp/trident/tree/master/contrib/ontap/trident_role["Gerador de funções personalizadas Trident"] Para obter mais informações sobre como criar funções personalizadas do Trident .

[role="tabbed-block"]
====
.Utilizando a CLI do ONTAP
--
. Crie uma nova função usando o seguinte comando:
+
`security login role create <role_name\> -cmddirname "command" -access all –vserver <svm_name\>`

. Crie um nome de usuário para o usuário do Trident :
+
`security login create -username <user_name\> -application ontapi -authmethod <password\> -role <name_of_role_in_step_1\> –vserver <svm_name\> -comment "user_description"`

. Atribua a função ao usuário:
+
`security login modify username <user_name\> –vserver <svm_name\> -role <role_name\> -application ontapi -application console -authmethod <password\>`



--
.Utilizando o Gerenciador de Sistemas
--
Execute as seguintes etapas no ONTAP System Manager:

. *Criar uma função personalizada*:
+
.. Para criar uma função personalizada no nível do cluster, selecione *Cluster > Configurações*.
+
(Ou) Para criar uma função personalizada no nível da SVM, selecione *Armazenamento > VMs de armazenamento > `required SVM` > Configurações > Usuários e funções*.

.. Selecione o ícone de seta (*->*) ao lado de *Usuários e Funções*.
.. Selecione *+Adicionar* em *Funções*.
.. Defina as regras para a função e clique em *Salvar*.


. *Atribua a função ao usuário do Trident *: + Execute as seguintes etapas na página *Usuários e Funções*:
+
.. Selecione o ícone Adicionar *** em *Usuários*.
.. Selecione o nome de usuário desejado e, em seguida, selecione uma função no menu suspenso *Função*.
.. Clique em *Salvar*.




--
====
Consulte as páginas seguintes para obter mais informações:

* link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/FAQ__Custom_roles_for_administration_of_ONTAP["Funções personalizadas para administração do ONTAP"^]oulink:https://docs.netapp.com/us-en/ontap/authentication/define-custom-roles-task.html["Defina funções personalizadas"^]
* link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_roles_users.html#rest-api["Trabalhar com funções e usuários"^]




== Autenticar conexões com CHAP bidirecional

O Trident pode autenticar sessões iSCSI com CHAP bidirecional para o `ontap-san` e `ontap-san-economy` motoristas.  Isso requer a ativação do `useCHAP` opção na sua definição de backend.  Quando definido para `true` O Trident configura a segurança do iniciador padrão da SVM para CHAP bidirecional e define o nome de usuário e os segredos a partir do arquivo de backend.  A NetApp recomenda o uso do protocolo CHAP bidirecional para autenticar conexões.  Veja a seguinte configuração de exemplo:

[source, yaml]
----
---
version: 1
storageDriverName: ontap-san
backendName: ontap_san_chap
managementLIF: 192.168.0.135
svm: ontap_iscsi_svm
useCHAP: true
username: vsadmin
password: password
chapInitiatorSecret: cl9qxIm36DKyawxy
chapTargetInitiatorSecret: rqxigXgkesIpwxyz
chapTargetUsername: iJF4heBRT0TCwxyz
chapUsername: uh2aNCLSd6cNwxyz
----

WARNING: O `useCHAP` O parâmetro é uma opção booleana que pode ser configurada apenas uma vez.  Por padrão, está definido como falso.  Depois de definir como verdadeiro, você não poderá definir como falso.

Além de `useCHAP=true` , o `chapInitiatorSecret` , `chapTargetInitiatorSecret` , `chapTargetUsername` , e `chapUsername` Os campos devem ser incluídos na definição do backend.  Os segredos podem ser alterados após a criação de um backend executando o seguinte comando: `tridentctl update` .



=== Como funciona

Ao configurar `useCHAP` Para confirmar, o administrador de armazenamento instrui o Trident a configurar o CHAP no backend de armazenamento. Isso inclui o seguinte:

* Configurando o CHAP no SVM:
+
** Se o tipo de segurança do iniciador padrão da SVM for "nenhum" (definido por padrão) *e* não houver LUNs preexistentes no volume, o Trident definirá o tipo de segurança padrão como `CHAP` e prossiga para a configuração do iniciador CHAP e do nome de usuário e segredos de destino.
** Se a SVM contiver LUNs, o Trident não habilitará o CHAP na SVM.  Isso garante que o acesso aos LUNs já presentes na SVM não seja restringido.


* Configurar o nome de usuário e os segredos do iniciador e do alvo CHAP; essas opções devem ser especificadas na configuração do backend (como mostrado acima).


Após a criação do backend, o Trident cria um correspondente. `tridentbackend` O CRD armazena os segredos CHAP e os nomes de usuário como segredos do Kubernetes.  Todos os PVs criados pelo Trident neste backend serão montados e conectados via CHAP.



=== Gire as credenciais e atualize os backends

Você pode atualizar as credenciais CHAP atualizando os parâmetros CHAP em `backend.json` arquivo.  Isso exigirá a atualização dos segredos CHAP e o uso do `tridentctl update` comando para refletir essas mudanças.


WARNING: Ao atualizar os segredos CHAP de um backend, você deve usar `tridentctl` para atualizar o backend.  Não atualize as credenciais no cluster de armazenamento usando a CLI do ONTAP ou o ONTAP System Manager, pois o Trident não conseguirá detectar essas alterações.

[listing]
----
cat backend-san.json
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "backendName": "ontap_san_chap",
    "managementLIF": "192.168.0.135",
    "svm": "ontap_iscsi_svm",
    "useCHAP": true,
    "username": "vsadmin",
    "password": "password",
    "chapInitiatorSecret": "cl9qxUpDaTeD",
    "chapTargetInitiatorSecret": "rqxigXgkeUpDaTeD",
    "chapTargetUsername": "iJF4heBRT0TCwxyz",
    "chapUsername": "uh2aNCLSd6cNwxyz",
}

./tridentctl update backend ontap_san_chap -f backend-san.json -n trident
+----------------+----------------+--------------------------------------+--------+---------+
|   NAME         | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+----------------+----------------+--------------------------------------+--------+---------+
| ontap_san_chap | ontap-san      | aa458f3b-ad2d-4378-8a33-1a472ffbeb5c | online |       7 |
+----------------+----------------+--------------------------------------+--------+---------+
----
As conexões existentes permanecerão inalteradas; elas continuarão ativas se as credenciais forem atualizadas pelo Trident no SVM.  Novas conexões utilizam as credenciais atualizadas e as conexões existentes permanecem ativas.  Desconectar e reconectar os sistemas fotovoltaicos antigos fará com que eles passem a usar as credenciais atualizadas.
