---
sidebar: sidebar 
permalink: trident-use/trident-fsx-install-trident.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident add-on, Trident EKS add-on, Trident AWS EKS add-on 
summary: 'Ao usar o Trident com o Amazon FSx for NetApp ONTAP, você garante que seus clusters Kubernetes em execução no Amazon Elastic Kubernetes Service (EKS) possam provisionar volumes persistentes em bloco e em arquivo com suporte do ONTAP.' 
---
= Instalar Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O Trident simplifica o gerenciamento de armazenamento do Amazon FSx for NetApp ONTAP no Kubernetes, permitindo que seus desenvolvedores e administradores se concentrem na implantação de aplicativos.

Você pode instalar o Trident usando um dos seguintes métodos:

* Leme
* Complemento EKS


Se você deseja utilizar a funcionalidade de instantâneo, instale o complemento CSI snapshot controller.  Consultelink:https://docs.aws.amazon.com/eks/latest/userguide/csi-snapshot-controller.html["Ative a funcionalidade de instantâneo para volumes CSI."^] para mais informações.



== Instale o Trident via Helm.

[role="tabbed-block"]
====
.Identidade do Pod
--
. Adicione o repositório Trident Helm:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Instale o Trident usando o seguinte exemplo:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace
----
+
Você pode usar o `helm list` Comando para revisar detalhes da instalação, como nome, namespace, gráfico, status, versão do aplicativo e número da revisão.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2502.0    25.02.0
----


--
.Associação de conta de serviço (IRSA)
--
. Adicione o repositório Trident Helm:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Defina os valores para *provedor de nuvem* e *identidade de nuvem*:
+
[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1  \
--set cloudProvider="AWS" \
--set cloudIdentity="'eks.amazonaws.com/role-arn: arn:aws:iam::<accountID>:role/<AmazonEKS_FSxN_CSI_DriverRole>'" \
--namespace trident \
--create-namespace
----
+
Você pode usar o `helm list` Comando para revisar detalhes da instalação, como nome, namespace, gráfico, status, versão do aplicativo e número da revisão.

+
[source, console]
----
helm list -n trident
----
+
[listing]
----
NAME                NAMESPACE   REVISION    UPDATED                                 STATUS       CHART                          APP VERSION

trident-operator    trident     1           2024-10-14 14:31:22.463122 +0300 IDT    deployed     trident-operator-100.2506.0    25.06.0
----


--
====
[NOTE]
====
Se você pretende usar iSCSI, certifique-se de que o iSCSI esteja habilitado em sua máquina cliente.  Se você estiver usando o sistema operacional de nó de trabalho AL2023, poderá automatizar a instalação do cliente iSCSI adicionando o parâmetro `node prep` na instalação do Helm:

[source, console]
----
helm install trident-operator netapp-trident/trident-operator --version 100.2502.1 --namespace trident --create-namespace –-set nodePrep={iscsi}
----
====


== Instale o Trident através do complemento EKS.

O complemento Trident EKS inclui os patches de segurança e correções de bugs mais recentes, e é validado pela AWS para funcionar com o Amazon EKS.  O complemento EKS permite garantir de forma consistente que seus clusters Amazon EKS estejam seguros e estáveis, além de reduzir o trabalho necessário para instalar, configurar e atualizar complementos.



=== Pré-requisitos

Certifique-se de ter o seguinte antes de configurar o complemento Trident para AWS EKS:

* Uma conta de cluster Amazon EKS com assinatura adicional.
* Permissões da AWS para o marketplace da AWS:
`"aws-marketplace:ViewSubscriptions",
"aws-marketplace:Subscribe",
"aws-marketplace:Unsubscribe`
* Tipo de AMI: Amazon Linux 2 (AL2_x86_64) ou Amazon Linux 2 Arm (AL2_ARM_64)
* Tipo de nó: AMD ou ARM
* Um sistema de arquivos Amazon FSx for NetApp ONTAP




=== Habilite o complemento Trident para AWS.

[role="tabbed-block"]
====
.Console de gerenciamento
--
. Abra o console do Amazon EKS em https://console.aws.amazon.com/eks/home#/clusters[] .
. No painel de navegação à esquerda, selecione *Clusters*.
. Selecione o nome do cluster para o qual deseja configurar o complemento NetApp Trident CSI.
. Selecione *Complementos* e depois selecione *Obter mais complementos*.
. Siga estes passos para selecionar o complemento:
+
.. Desça a página até a seção *Complementos do AWS Marketplace* e digite *"Trident"* na caixa de pesquisa.
.. Selecione a caixa de seleção no canto superior direito da caixa Trident by NetApp .
.. Selecione *Avançar*.


. Na página de configurações *Configurar complementos selecionados*, faça o seguinte:
+

NOTE: *Ignore estas etapas se estiver usando a associação de identidade do Pod.*

+
.. Selecione a *Versão* que deseja usar.
.. Se você estiver usando a autenticação IRSA, certifique-se de definir os valores de configuração disponíveis nas Configurações opcionais:
+
*** Selecione a *Versão* que deseja usar.
*** Siga o *esquema de configuração do complemento* e defina o parâmetro *configurationValues* na seção *Valores de configuração* com o role-arn que você criou na etapa anterior (o valor deve estar no seguinte formato):




+
[source, JSON]
----
{

  "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
  "cloudProvider": "AWS"

}
----
+
Se você selecionar "Substituir" como método de resolução de conflitos, uma ou mais configurações do complemento existente poderão ser substituídas pelas configurações do complemento do Amazon EKS.  Se você não ativar essa opção e houver um conflito com suas configurações existentes, a operação falhará.  Você pode usar a mensagem de erro resultante para solucionar o conflito.  Antes de selecionar esta opção, certifique-se de que o complemento Amazon EKS não gerencie configurações que você precise gerenciar manualmente.

. Selecione *Próximo*.
. Na página *Revisar e adicionar*, escolha *Criar*.
+
Após a conclusão da instalação do complemento, você verá o complemento instalado.



--
.CLI da AWS
--
*1. Crie o `add-on.json` arquivo*:

*Para a identidade do Pod, utilize o seguinte formato*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
}
----
*Para autenticação IRSA, utilize o seguinte formato*:

[source, json]
----
{
  "clusterName": "<eks-cluster>",
  "addonName": "netapp_trident-operator",
  "addonVersion": "v25.6.0-eksbuild.1",
  "serviceAccountRoleArn": "<role ARN>",
  "configurationValues": {
    "cloudIdentity": "'eks.amazonaws.com/role-arn: <role ARN>'",
    "cloudProvider": "AWS"
  }
}
----

NOTE: Substituir `<role ARN>` com o ARN da função que foi criada na etapa anterior.

*2. Instale o complemento Trident EKS.*

[source, console]
----
aws eks create-addon --cli-input-json file://add-on.json
----
--
.eksctl
--
O comando de exemplo a seguir instala o complemento Trident EKS:

[source, console]
----
eksctl create addon --name netapp_trident-operator --cluster <cluster_name> --force
----
--
====


=== Atualize o complemento Trident EKS.

[role="tabbed-block"]
====
.Console de gerenciamento
--
. Abra o console do Amazon EKS https://console.aws.amazon.com/eks/home#/clusters[] .
. No painel de navegação à esquerda, selecione *Clusters*.
. Selecione o nome do cluster para o qual deseja atualizar o complemento NetApp Trident CSI.
. Selecione a aba *Complementos*.
. Selecione * Trident by NetApp* e depois selecione *Editar*.
. Na página *Configurar Trident by NetApp*, faça o seguinte:
+
.. Selecione a *Versão* que deseja usar.
.. Expanda as *Configurações opcionais* e modifique conforme necessário.
.. Selecione *Salvar alterações*.




--
.CLI da AWS
--
O exemplo a seguir atualiza o complemento EKS:

[source, console]
----
aws eks update-addon --cluster-name <eks_cluster_name> --addon-name netapp_trident-operator --addon-version v25.6.0-eksbuild.1 \
  --service-account-role-arn <role-ARN> --resolve-conflict preserve \
  --configuration-values “{\"cloudIdentity\": \"'eks.amazonaws.com/role-arn: <role ARN>'\"}"
----
--
.eksctl
--
* Verifique a versão atual do seu complemento FSxN Trident CSI.  Substituir `my-cluster` com o nome do seu cluster.
+
[source, console]
----
eksctl get addon --name netapp_trident-operator --cluster my-cluster
----
+
*Exemplo de saída:*



[listing]
----
NAME                        VERSION             STATUS    ISSUES    IAMROLE    UPDATE AVAILABLE    CONFIGURATION VALUES
netapp_trident-operator    v25.6.0-eksbuild.1    ACTIVE    0       {"cloudIdentity":"'eks.amazonaws.com/role-arn: arn:aws:iam::139763910815:role/AmazonEKS_FSXN_CSI_DriverRole'"}
----
* Atualize o complemento para a versão retornada em ATUALIZAÇÃO DISPONÍVEL na saída da etapa anterior.
+
[source, console]
----
eksctl update addon --name netapp_trident-operator --version v25.6.0-eksbuild.1 --cluster my-cluster --force
----


Se você remover o `--force` Se alguma das opções e configurações do complemento do Amazon EKS entrarem em conflito com suas configurações existentes, a atualização do complemento do Amazon EKS falhará e você receberá uma mensagem de erro para ajudá-lo a resolver o conflito.  Antes de especificar esta opção, certifique-se de que o complemento Amazon EKS não gerencie configurações que você precisa gerenciar, pois essas configurações serão sobrescritas com esta opção.  Para obter mais informações sobre outras opções para esta configuração, consultelink:https://eksctl.io/usage/addons/["Complementos"] .  Para obter mais informações sobre o gerenciamento de campos do Kubernetes no Amazon EKS, consultelink:https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-field-management.html["gerenciamento de campos do Kubernetes"] .

--
====


=== Desinstale/remova o complemento Trident EKS.

Você tem duas opções para remover um complemento do Amazon EKS:

* *Preservar software adicional no seu cluster* – Esta opção remove o gerenciamento de quaisquer configurações pelo Amazon EKS.  Isso também remove a capacidade do Amazon EKS de notificá-lo sobre atualizações e de atualizar automaticamente o complemento do Amazon EKS após você iniciar uma atualização.  No entanto, isso preserva o software adicional no seu cluster.  Essa opção transforma o complemento em uma instalação autogerenciada, em vez de um complemento do Amazon EKS.  Com essa opção, não há tempo de inatividade para o complemento.  Mantenha o `--preserve` opção no comando para preservar o complemento.
* *Remova completamente o software complementar do seu cluster* – A NetApp recomenda que você remova o complemento Amazon EKS do seu cluster somente se não houver recursos no seu cluster que dependam dele.  Remova o `--preserve` opção da `delete` comando para remover o complemento.



NOTE: Se o complemento tiver uma conta IAM associada a ele, essa conta IAM não será removida.

[role="tabbed-block"]
====
.Console de gerenciamento
--
. Abra o console do Amazon EKS em https://console.aws.amazon.com/eks/home#/clusters[] .
. No painel de navegação à esquerda, selecione *Clusters*.
. Selecione o nome do cluster para o qual deseja remover o complemento NetApp Trident CSI.
. Selecione a guia *Complementos* e, em seguida, selecione * Trident by NetApp*.
. Selecione *Remover*.
. Na caixa de diálogo *Remover confirmação do netapp_trident-operator*, faça o seguinte:
+
.. Se você deseja que o Amazon EKS pare de gerenciar as configurações do complemento, selecione *Preservar no cluster*.  Faça isso se quiser manter o software complementar no seu cluster para poder gerenciar todas as configurações do complemento por conta própria.
.. Digite *netapp_trident-operator*.
.. Selecione *Remover*.




--
.CLI da AWS
--
Substituir `my-cluster` com o nome do seu cluster e, em seguida, execute o seguinte comando.

[source, console]
----
aws eks delete-addon --cluster-name my-cluster --addon-name netapp_trident-operator --preserve
----
--
.eksctl
--
O comando a seguir desinstala o complemento Trident EKS:

[source, console]
----
eksctl delete addon --cluster K8s-arm --name netapp_trident-operator
----
--
====