---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator, smb, windows 
summary: 'O operador Trident permite personalizar a forma como o Trident Ă© instalado, utilizando os atributos em `TridentOrchestrator` especificaĂ§ĂŁo.' 
---
= Personalize a instalaĂ§ĂŁo do operador Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O operador Trident permite personalizar a instalaĂ§ĂŁo do Trident usando os atributos em `TridentOrchestrator` especificaĂ§ĂŁo.  Se vocĂȘ deseja personalizar a instalaĂ§ĂŁo alĂ©m do que... `TridentOrchestrator` Se os argumentos permitirem, considere usar `tridentctl` para gerar manifestos YAML personalizados que podem ser modificados conforme necessĂĄrio.



== Entendendo os pods do controlador e os pods do nĂł

O Trident Ă© executado como um Ășnico pod de controlador, alĂ©m de um pod de nĂł em cada nĂł de trabalho do cluster.  O pod do nĂł deve estar em execuĂ§ĂŁo em qualquer host onde vocĂȘ queira potencialmente montar um volume Trident .

Kuberneteslink:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["seletores de nĂłs"^] elink:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["tolerĂąncias e contaminaĂ§Ă”es"^] SĂŁo utilizadas para restringir a execuĂ§ĂŁo de um pod a um nĂł especĂ­fico ou preferencial.  Usando o `ControllerPlugin` e `NodePlugin` VocĂȘ pode especificar restriĂ§Ă”es e substituiĂ§Ă”es.

* O plugin do controlador lida com o provisionamento e gerenciamento de volumes, como snapshots e redimensionamento.
* O plugin do nĂł gerencia a conexĂŁo do armazenamento ao nĂł.




== OpĂ§Ă”es de configuraĂ§ĂŁo


WARNING: `spec.namespace`Ă© especificado em `TridentOrchestrator` para indicar o espaĂ§o de nomes onde o Trident estĂĄ instalado.  Este parĂąmetro *nĂŁo pode ser atualizado apĂłs a instalaĂ§ĂŁo do Trident *.  Tentar fazer isso causa o `TridentOrchestrator` status para alterar para `Failed` .  O Trident nĂŁo foi projetado para ser migrado entre namespaces.

Esta tabela detalha `TridentOrchestrator` atributos.

[cols="1,2,1"]
|===
| ParĂąmetro | DescriĂ§ĂŁo | PadrĂŁo 


| `namespace` | Namespace para instalar o Trident em | `"default"` 


| `debug` | Ative a depuraĂ§ĂŁo para o Trident. | `false` 


| `enableForceDetach` | `ontap-san`, `ontap-san-economy` , `ontap-nas` , e `ontap-nas-economy` apenas.  Funciona com o recurso Non-Graceful Node Shutdown (NGNS) do Kubernetes para permitir que os administradores do cluster migrem cargas de trabalho com volumes montados para novos nĂłs com seguranĂ§a, caso um nĂł apresente problemas. | `false` 


| `windows` | Configurando para `true` Permite a instalaĂ§ĂŁo em nĂłs de trabalho do Windows. | `false` 


| `cloudProvider`  a| 
Definir para `"Azure"` Ao usar identidades gerenciadas ou uma identidade na nuvem em um cluster AKS.  Definir para `"AWS"` Ao usar uma identidade de nuvem em um cluster EKS.  Definir para `"GCP"` Ao usar uma identidade de nuvem em um cluster GKE.
| `""` 


| `cloudIdentity`  a| 
Defina a identidade da carga de trabalho ("azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx") ao usar a identidade da nuvem em um cluster AKS.  Defina a funĂ§ĂŁo do AWS IAM ("'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/trident-role'") ao usar a identidade na nuvem em um cluster EKS.  Defina a identidade na nuvem ("'iam.gke.io/gcp-service-account: xxxx@mygcpproject.iam.gserviceaccount.com'") ao usar a identidade na nuvem em um cluster GKE.
| `""` 


| `IPv6` | Instalar Trident via IPv6 | falso 


| `k8sTimeout`  a| 
Tempo limite para operaĂ§Ă”es do Kubernetes.


NOTE: O `k8sTimeout` Este parĂąmetro aplica-se apenas Ă  instalaĂ§ĂŁo do Trident .
| `180sec` 


| `silenceAutosupport` | NĂŁo envie pacotes de suporte automĂĄtico para a NetApp automaticamente. | `false` 


| `autosupportImage` | A imagem do contĂȘiner para Telemetria de Suporte AutomĂĄtico | `"netapp/trident-autosupport:25.06"` 


| `autosupportProxy` | O endereĂ§o/porta de um proxy para envio de telemetria do Autosupport. | `"http://proxy.example.com:8888"` 


| `uninstall` | Uma flag usada para desinstalar o Trident. | `false` 


| `logFormat` | Formato de registro do Trident a ser usado [texto,json] | `"text"` 


| `tridentImage` | Imagem Trident para instalar | `"netapp/trident:25.06"` 


| `imageRegistry` | Caminho para o registro interno, no formato
`<registry FQDN>[:port][/subpath]` | `"registry.k8s.io"` 


| `kubeletDir` | Caminho para o diretĂłrio kubelet no host | `"/var/lib/kubelet"` 


| `wipeout` | Lista de recursos a serem excluĂ­dos para remover completamente o Trident. |  


| `imagePullSecrets` | Segredos para extrair imagens de um registro interno |  


| `imagePullPolicy` | Define a polĂ­tica de extraĂ§ĂŁo de imagens para o operador Trident .  Os valores vĂĄlidos sĂŁo:
`Always` sempre extrair a imagem. 
`IfNotPresent` Para extrair a imagem somente se ela ainda nĂŁo existir no nĂł. 
`Never` Nunca retire a imagem. | `IfNotPresent` 


| `controllerPluginNodeSelector` | Seletores de nĂłs adicionais para pods.  Segue o mesmo formato que `pod.spec.nodeSelector` . | Sem valor padrĂŁo; opcional 


| `controllerPluginTolerations` | Substitui as tolerĂąncias do Kubernetes para pods.  Segue o mesmo formato que `pod.spec.Tolerations` . | Sem valor padrĂŁo; opcional 


| `nodePluginNodeSelector` | Seletores de nĂłs adicionais para pods.  Segue o mesmo formato que `pod.spec.nodeSelector` . | Sem valor padrĂŁo; opcional 


| `nodePluginTolerations` | Substitui as tolerĂąncias do Kubernetes para pods.  Segue o mesmo formato que `pod.spec.Tolerations` . | Sem valor padrĂŁo; opcional 


| `nodePrep`  a| 
Permite que o Trident prepare os nĂłs do cluster Kubernetes para gerenciar volumes usando o protocolo de armazenamento de dados especificado. *Atualmente, `iscsi` Ă© o Ășnico valor suportado.*


NOTE: A partir do OpenShift 4.19, a versĂŁo mĂ­nima do Trident suportada para esse recurso Ă© 25.06.1.
|  


| `k8sAPIQPS`  a| 
O limite de consultas por segundo (QPS) usado pelo controlador durante a comunicaĂ§ĂŁo com o servidor da API do Kubernetes. O valor de Burst Ă© definido automaticamente com base no valor QPS.
| `100`; opcional 


| `enableConcurrency`  a| 
Permite operaĂ§Ă”es simultĂąneas do controlador Trident para melhor rendimento.


NOTE: *VisualizaĂ§ĂŁo tĂ©cnica*: Este recurso Ă© experimental no NetApp Trident 25.06 e atualmente oferece suporte a fluxos de trabalho paralelos limitados com o driver ONTAP-SAN (protocolos iSCSI e FCP).
| falso 
|===

NOTE: Para obter mais informaĂ§Ă”es sobre como formatar parĂąmetros de pod, consultelink:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["Atribuindo Pods a NĂłs"^] .



=== Detalhes sobre o desprendimento forĂ§ado

O desprendimento forĂ§ado estĂĄ disponĂ­vel para `ontap-san` , `ontap-san-economy` , `ontap-nas` , e `ontap-nas-economy` apenas. Antes de habilitar a desconexĂŁo forĂ§ada, o desligamento nĂŁo normal do nĂł (NGNS) deve ser habilitado no cluster do Kubernetes. O NGNS Ă© habilitado por padrĂŁo para o Kubernetes 1.28 e superior.  Para obter mais informaĂ§Ă”es, consultelink:https://kubernetes.io/docs/concepts/cluster-administration/node-shutdown/#non-graceful-node-shutdown["Kubernetes: Encerramento abrupto de nĂłs"^] .


NOTE: Ao usar o `ontap-nas` ou `ontap-nas-economy` Motorista, vocĂȘ precisa configurar o `autoExportPolicy` parĂąmetro na configuraĂ§ĂŁo do backend para `true` para que o Trident possa restringir o acesso do nĂł Kubernetes com a restriĂ§ĂŁo aplicada usando polĂ­ticas de exportaĂ§ĂŁo gerenciadas.


WARNING: Como o Trident depende do Kubernetes NGNS, nĂŁo o remova. `out-of-service` contaminaĂ§Ă”es de um nĂł nĂŁo saudĂĄvel atĂ© que todas as cargas de trabalho intolerĂĄveis ââsejam reprogramadas.  Aplicar ou remover a contaminaĂ§ĂŁo de forma imprudente pode comprometer a proteĂ§ĂŁo de dados no sistema.

Quando o administrador do cluster Kubernetes aplicou o `node.kubernetes.io/out-of-service=nodeshutdown:NoExecute` contaminar o nĂł e `enableForceDetach` estĂĄ definido para `true` O Trident determinarĂĄ o estado do nĂł e:

. Interrompa o acesso de E/S de backend para volumes montados nesse nĂł.
. Marque o objeto do nĂł Trident como `dirty` (NĂŁo recomendado para novas publicaĂ§Ă”es).
+

NOTE: O controlador Trident rejeitarĂĄ novas solicitaĂ§Ă”es de publicaĂ§ĂŁo de volume atĂ© que o nĂł seja requalificado (apĂłs ter sido marcado como `dirty` ) pelo pod do nĂł Trident .  Quaisquer cargas de trabalho agendadas com um PVC montado (mesmo apĂłs o nĂł do cluster estar Ă­ntegro e pronto) nĂŁo serĂŁo aceitas atĂ© que o Trident possa verificar o nĂł. `clean` (Seguro para novas publicaĂ§Ă”es).



Quando a integridade do nĂł for restaurada e a contaminaĂ§ĂŁo for removida, o Trident farĂĄ o seguinte:

. Identificar e limpar caminhos publicados obsoletos no nĂł.
. Se o nĂł estiver em um `cleanable` estado (a marcaĂ§ĂŁo de fora de serviĂ§o foi removida e o nĂł estĂĄ em `Ready` estado) e todos os caminhos obsoletos e publicados estĂŁo limpos, o Trident readmitirĂĄ o nĂł como `clean` e permitir que novos volumes publicados sejam enviados ao nĂł.




== ConfiguraĂ§Ă”es de exemplo

VocĂȘ pode usar os atributos em<<OpĂ§Ă”es de configuraĂ§ĂŁo>> ao definir `TridentOrchestrator` Para personalizar sua instalaĂ§ĂŁo.

.ConfiguraĂ§ĂŁo personalizada bĂĄsica
[%collapsible]
====
Este exemplo foi criado apĂłs a execuĂ§ĂŁo do `cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml` O comando representa uma instalaĂ§ĂŁo personalizada bĂĄsica:

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
====
.Seletores de nĂłs
[%collapsible]
====
Este exemplo instala o Trident com seletores de nĂłs.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
====
.nĂłs de trabalho do Windows
[%collapsible]
====
Este exemplo foi criado apĂłs a execuĂ§ĂŁo do `cat deploy/crds/tridentorchestrator_cr.yaml` O comando instala o Trident em um nĂł de trabalho do Windows.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  windows: true
----
====
.Identidades gerenciadas em um cluster AKS
[%collapsible]
====
Este exemplo instala o Trident para habilitar identidades gerenciadas em um cluster AKS.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  cloudProvider: "Azure"
----
====
.Identidade na nuvem em um cluster AKS
[%collapsible]
====
Este exemplo instala o Trident para uso com uma identidade na nuvem em um cluster AKS.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  cloudProvider: "Azure"
  cloudIdentity: 'azure.workload.identity/client-id: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx'

----
====
.Identidade na nuvem em um cluster EKS
[%collapsible]
====
Este exemplo instala o Trident para uso com uma identidade na nuvem em um cluster AKS.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  cloudProvider: "AWS"
  cloudIdentity: "'eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/trident-role'"
----
====
.Identidade na nuvem para GKE
[%collapsible]
====
Este exemplo instala o Trident para uso com uma identidade na nuvem em um cluster GKE.

[source, yaml]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-gcp-gcnv
spec:
  version: 1
  storageDriverName: google-cloud-netapp-volumes
  projectNumber: '012345678901'
  network: gcnv-network
  location: us-west2
  serviceLevel: Premium
  storagePool: pool-premium1
----
====