---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm-mirror.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, offline, air gap, gap, registry 
summary: VocĂȘ pode implantar o operador Trident e instalar o Trident usando o Helm.  Este processo aplica-se a instalaĂ§Ă”es onde as imagens de contĂȘiner exigidas pelo Trident estĂŁo armazenadas em um registro privado. 
---
= Implantar operador Trident usando Helm (modo offline)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VocĂȘ pode implantar o operador Trident e instalar o Trident usando o Helm.  Este processo aplica-se a instalaĂ§Ă”es onde as imagens de contĂȘiner exigidas pelo Trident estĂŁo armazenadas em um registro privado.  Se vocĂȘ nĂŁo possui um registro de imagens privado, utilize olink:kubernetes-deploy-helm.html["processo para implantaĂ§ĂŁo padrĂŁo"] .



== InformaĂ§Ă”es crĂ­ticas sobre o Trident 25.06

*VocĂȘ deve ler as seguintes informaĂ§Ă”es crĂ­ticas sobre Trident.*

.<strong>InformaĂ§Ă”es crĂ­ticas sobre o Trident</strong>
[%collapsible%open]
====
[]
=====
* O Kubernetes 1.34 agora Ă© compatĂ­vel com o Trident. Atualize o Trident antes de atualizar o Kubernetes.
* A Trident impĂ”e rigorosamente o uso da configuraĂ§ĂŁo de multipathing em ambientes SAN, com um valor recomendado de `find_multipaths: no` no arquivo multipath.conf.
+
UtilizaĂ§ĂŁo de configuraĂ§ĂŁo sem multipathing ou utilizaĂ§ĂŁo de `find_multipaths: yes` ou `find_multipaths: smart` O valor no arquivo multipath.conf resultarĂĄ em falhas de montagem.  A Trident recomendou o uso de `find_multipaths: no` desde a versĂŁo de 21/07.



=====
====


== Implante o operador Trident e instale o Trident usando o Helm.

Usando o Tridentlink:https://netapp.github.io/trident-helm-chart["Carta do leme"^] VocĂȘ pode implantar o operador Trident e instalar o Trident em uma Ășnica etapa.

AnĂĄliselink:../trident-get-started/kubernetes-deploy.html["visĂŁo geral da instalaĂ§ĂŁo"] Para garantir que vocĂȘ atendeu aos prĂ©-requisitos de instalaĂ§ĂŁo e selecionou a opĂ§ĂŁo de instalaĂ§ĂŁo correta para o seu ambiente.

.Antes de comeĂ§ar
AlĂ©m dolink:../trident-get-started/kubernetes-deploy.html#before-you-deploy["prĂ©-requisitos de implantaĂ§ĂŁo"] vocĂȘ precisalink:https://v3.helm.sh/["Helm versĂŁo 3"^] .


IMPORTANT: Ao instalar o Trident em um repositĂłrio privado, se vocĂȘ estiver usando o `imageRegistry` Para especificar a localizaĂ§ĂŁo do repositĂłrio, nĂŁo use a opĂ§ĂŁo `--change`. `/netapp/` no caminho do repositĂłrio.

.Passos
. Adicione o repositĂłrio Trident Helm:
+
[source, console]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. Usar `helm install` Especifique um nome para sua implantaĂ§ĂŁo e o local do registro de imagens.  Seulink:../trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions["Imagens do Trident e do CSI"] Podem estar localizadas em um Ășnico registro ou em registros diferentes, mas todas as imagens CSI devem estar localizadas no mesmo registro.  Nos exemplos, `100.2506.0` Ă© a versĂŁo do Trident que vocĂȘ estĂĄ instalando.
+
[role="tabbed-block"]
====
.Imagens em um Ășnico registro
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
.Imagens em diferentes registros
--
[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --set imageRegistry=<your-registry> --set operatorImage=<your-registry>/trident-operator:25.06.0 --set tridentAutosupportImage=<your-registry>/trident-autosupport:25.06 --set tridentImage=<your-registry>/trident:25.06.0 --create-namespace --namespace <trident-namespace> --set nodePrep={iscsi}
----
--
====
+

NOTE: Se vocĂȘ jĂĄ criou um namespace para o Trident, o `--create-namespace` O parĂąmetro nĂŁo criarĂĄ um namespace adicional.



VocĂȘ pode usar `helm list` Para analisar detalhes da instalaĂ§ĂŁo, como nome, namespace, grĂĄfico, status, versĂŁo do aplicativo e nĂșmero da revisĂŁo.



== Passe os dados de configuraĂ§ĂŁo durante a instalaĂ§ĂŁo.

Existem duas maneiras de passar dados de configuraĂ§ĂŁo durante a instalaĂ§ĂŁo:

[cols="2"]
|===
| OpĂ§ĂŁo | DescriĂ§ĂŁo 


| `--values`(ou `-f` )  a| 
Especifique um arquivo YAML com as configuraĂ§Ă”es personalizadas.  Isso pode ser especificado vĂĄrias vezes e o arquivo mais Ă  direita terĂĄ precedĂȘncia.



| `--set`  a| 
Especifique as configuraĂ§Ă”es alternativas na linha de comando.

|===
Por exemplo, para alterar o valor padrĂŁo de `debug` , execute o seguinte comando onde `100.2506.0` Esta Ă© a versĂŁo do Trident que vocĂȘ estĂĄ instalando:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----
Para adicionar o valor nodePrep, execute o seguinte comando:

[source, console]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set nodePrep={iscsi}
----


== OpĂ§Ă”es de configuraĂ§ĂŁo

Esta tabela e a `values.yaml` O arquivo, que faz parte do grĂĄfico Helm, fornece a lista de chaves e seus valores padrĂŁo.


WARNING: NĂŁo remova a afinidade padrĂŁo do arquivo values.yaml.  Quando vocĂȘ quiser fornecer uma afinidade personalizada, estenda a afinidade padrĂŁo.

[cols="3"]
|===
| OpĂ§ĂŁo | DescriĂ§ĂŁo | PadrĂŁo 


| `nodeSelector` | RĂłtulos de nĂłs para atribuiĂ§ĂŁo de pods |  


| `podAnnotations` | AnotaĂ§Ă”es de pods |  


| `deploymentAnnotations` | AnotaĂ§Ă”es de implantaĂ§ĂŁo |  


| `tolerations` | TolerĂąncias para atribuiĂ§ĂŁo de pods |  


| `affinity` | Afinidade pela atribuiĂ§ĂŁo de cĂĄpsulas  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: NĂŁo remova a afinidade padrĂŁo do arquivo values.yaml.  Quando vocĂȘ quiser fornecer uma afinidade personalizada, estenda a afinidade padrĂŁo.



| `tridentControllerPluginNodeSelector` | Seletores de nĂłs adicionais para pods. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Entendendo os pods do controlador e os pods do nĂł"] para mais detalhes. |  


| `tridentControllerPluginTolerations` | Substitui as tolerĂąncias do Kubernetes para pods. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Entendendo os pods do controlador e os pods do nĂł"] para mais detalhes. |  


| `tridentNodePluginNodeSelector` | Seletores de nĂłs adicionais para pods. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Entendendo os pods do controlador e os pods do nĂł"] para mais detalhes. |  


| `tridentNodePluginTolerations` | Substitui as tolerĂąncias do Kubernetes para pods. Consulte link:../trident-get-started/architecture.html#understanding-controller-pods-and-node-pods["Entendendo os pods do controlador e os pods do nĂł"] para mais detalhes. |  


| `imageRegistry` | Identifica o registro para o `trident-operator` , `trident` e outras imagens.  Deixe em branco para aceitar o valor padrĂŁo.  IMPORTANTE: Ao instalar o Trident em um repositĂłrio privado, se vocĂȘ estiver usando o `imageRegistry` Para especificar a localizaĂ§ĂŁo do repositĂłrio, nĂŁo use a opĂ§ĂŁo `--change`. `/netapp/` no caminho do repositĂłrio. | "" 


| `imagePullPolicy` | Define a polĂ­tica de extraĂ§ĂŁo de imagens para o `trident-operator` . | `IfNotPresent` 


| `imagePullSecrets` | Define os segredos de extraĂ§ĂŁo de imagens para o `trident-operator` , `trident` e outras imagens. |  


| `kubeletDir` | Permite substituir a localizaĂ§ĂŁo do host do estado interno do kubelet. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Permite definir o nĂ­vel de registro do operador Trident para: `trace` , `debug` , `info` , `warn` , `error` , ou `fatal` . | `"info"` 


| `operatorDebug` | Permite definir o nĂ­vel de registro do operador Trident como depuraĂ§ĂŁo. | `true` 


| `operatorImage` | Permite a substituiĂ§ĂŁo completa da imagem para `trident-operator` . | "" 


| `operatorImageTag` | Permite sobrescrever a tag do `trident-operator` imagem. | "" 


| `tridentIPv6` | Permite habilitar o Trident para funcionar em clusters IPv6. | `false` 


| `tridentK8sTimeout`  a| 
Substitui o tempo limite padrĂŁo de 180 segundos para a maioria das operaĂ§Ă”es da API do Kubernetes (se diferente de zero, em segundos).


NOTE: O `tridentK8sTimeout` Este parĂąmetro aplica-se apenas Ă  instalaĂ§ĂŁo do Trident .
| `180` 


| `tridentHttpRequestTimeout` | Substitui o tempo limite padrĂŁo de 90 segundos para as solicitaĂ§Ă”es HTTP, com `0s` sendo uma duraĂ§ĂŁo infinita para o tempo limite.  Valores negativos nĂŁo sĂŁo permitidos. | `"90s"` 


| `tridentSilenceAutosupport` | Permite desativar o relatĂłrio periĂłdico do AutoSupport do Trident . | `false` 


| `tridentAutosupportImageTag` | Permite substituir a tag da imagem para o contĂȘiner Trident AutoSupport . | `<version>` 


| `tridentAutosupportProxy` | Permite que o contĂȘiner Trident AutoSupport se comunique com servidores externos atravĂ©s de um proxy HTTP. | "" 


| `tridentLogFormat` | Define o formato de registro do Trident.(`text` ou `json` ). | `"text"` 


| `tridentDisableAuditLog` | Desativa o registrador de auditoria do Trident . | `true` 


| `tridentLogLevel` | Permite definir o nĂ­vel de registro do Trident para: `trace` , `debug` , `info` , `warn` , `error` , ou `fatal` . | `"info"` 


| `tridentDebug` | Permite definir o nĂ­vel de registro do Trident para `debug` . | `false` 


| `tridentLogWorkflows` | Permite que fluxos de trabalho especĂ­ficos do Trident sejam habilitados para registro de rastreamento ou supressĂŁo de logs. | "" 


| `tridentLogLayers` | Permite que camadas especĂ­ficas do Trident sejam ativadas para registro de rastreamento ou supressĂŁo de logs. | "" 


| `tridentImage` | Permite a substituiĂ§ĂŁo completa da imagem para o Trident. | "" 


| `tridentImageTag` | Permite sobrescrever a tag da imagem para o Trident. | "" 


| `tridentProbePort` | Permite alterar a porta padrĂŁo usada para as sondagens de atividade/prontidĂŁo do Kubernetes. | "" 


| `windows` | Permite a instalaĂ§ĂŁo do Trident em nĂłs de trabalho Windows. | `false` 


| `enableForceDetach` | Permite ativar a funĂ§ĂŁo de desprendimento forĂ§ado. | `false` 


| `excludePodSecurityPolicy` | Exclui a polĂ­tica de seguranĂ§a do pod do operador da criaĂ§ĂŁo. | `false` 


| `nodePrep`  a| 
Permite que o Trident prepare os nĂłs do cluster Kubernetes para gerenciar volumes usando o protocolo de armazenamento de dados especificado. *Atualmente, `iscsi` Ă© o Ășnico valor suportado.*


NOTE: A partir do OpenShift 4.19, a versĂŁo mĂ­nima do Trident suportada para esse recurso Ă© 25.06.1.
|  
|===