---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-operator.html 
keywords: deploy, Trident, methods, operator, tridentctl, registry, registries 
summary: VocĂȘ pode implantar manualmente o operador Trident para instalar o Trident.  Este processo aplica-se a instalaĂ§Ă”es onde as imagens de contĂȘiner exigidas pelo Trident nĂŁo estĂŁo armazenadas em um registro privado. 
---
= ImplantaĂ§ĂŁo manual do operador Trident (modo padrĂŁo)
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VocĂȘ pode implantar manualmente o operador Trident para instalar o Trident.  Este processo aplica-se a instalaĂ§Ă”es onde as imagens de contĂȘiner exigidas pelo Trident nĂŁo estĂŁo armazenadas em um registro privado.  Se vocĂȘ tiver um registro de imagens privado, use olink:kubernetes-deploy-operator-mirror.html["processo para implantaĂ§ĂŁo offline"] .



== InformaĂ§Ă”es crĂ­ticas sobre o Trident 25.06

*VocĂȘ deve ler as seguintes informaĂ§Ă”es crĂ­ticas sobre Trident.*

.<strong>InformaĂ§Ă”es crĂ­ticas sobre o Trident</strong>
[%collapsible%open]
====
[]
=====
* O Kubernetes 1.34 agora Ă© compatĂ­vel com o Trident. Atualize o Trident antes de atualizar o Kubernetes.
* A Trident impĂ”e rigorosamente o uso da configuraĂ§ĂŁo de multipathing em ambientes SAN, com um valor recomendado de `find_multipaths: no` no arquivo multipath.conf.
+
UtilizaĂ§ĂŁo de configuraĂ§ĂŁo sem multipathing ou utilizaĂ§ĂŁo de `find_multipaths: yes` ou `find_multipaths: smart` O valor no arquivo multipath.conf resultarĂĄ em falhas de montagem.  A Trident recomendou o uso de `find_multipaths: no` desde a versĂŁo de 21/07.



=====
====


== Implante manualmente o operador Trident e instale o Trident.

AnĂĄliselink:../trident-get-started/kubernetes-deploy.html["visĂŁo geral da instalaĂ§ĂŁo"] Para garantir que vocĂȘ atendeu aos prĂ©-requisitos de instalaĂ§ĂŁo e selecionou a opĂ§ĂŁo de instalaĂ§ĂŁo correta para o seu ambiente.

.Antes de comeĂ§ar
Antes de iniciar a instalaĂ§ĂŁo, faĂ§a login no host Linux e verifique se ele estĂĄ gerenciando um sistema operacional em funcionamento.link:requirements.html["cluster Kubernetes suportado"^] e que vocĂȘ possui os privilĂ©gios necessĂĄrios.


NOTE: Com o OpenShift, use `oc` em vez de `kubectl` Em todos os exemplos a seguir, faĂ§a login como *system:admin* primeiro executando o seguinte comando: `oc login -u system:admin` ou `oc login -u kube-admin` .

[%collapsible%open]
====
. Verifique sua versĂŁo do Kubernetes:
+
[listing]
----
kubectl version
----
. Verificar privilĂ©gios de administrador do cluster:
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Verifique se vocĂȘ consegue iniciar um pod que utiliza uma imagem do Docker Hub e acessar seu sistema de armazenamento atravĂ©s da rede de pods:
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


=== Passo 1: Baixe o pacote de instalaĂ§ĂŁo do Trident

O pacote de instalaĂ§ĂŁo do Trident contĂ©m tudo o que vocĂȘ precisa para implantar o operador Trident e instalar o Trident.  Baixe e extraia a versĂŁo mais recente do instalador do Trident emlink:https://github.com/NetApp/trident/releases/latest["a seĂ§ĂŁo _Assets_ no GitHub"^] .

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v25.06.0/trident-installer-25.06.0.tar.gz
tar -xf trident-installer-25.06.0.tar.gz
cd trident-installer
----


=== Passo 2: Crie o `TridentOrchestrator` CRD

Crie o `TridentOrchestrator` DefiniĂ§ĂŁo de Recurso Personalizado (CRD).  VocĂȘ criarĂĄ um `TridentOrchestrator` Recurso personalizado mais tarde.  Use a versĂŁo YAML do CRD apropriada em `deploy/crds` para criar o `TridentOrchestrator` CRD.

[listing]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----


=== Etapa 3: Implante o operador Trident

O instalador do Trident fornece um arquivo de pacote que pode ser usado para instalar o operador e criar objetos associados.  O arquivo de pacote Ă© uma maneira fĂĄcil de implantar o operador e instalar o Trident usando uma configuraĂ§ĂŁo padrĂŁo.

* Para clusters executando Kubernetes 1.24, use `bundle_pre_1_25.yaml` .
* Para clusters executando Kubernetes 1.25 ou posterior, use `bundle_post_1_25.yaml` .


.Antes de comeĂ§ar
* Por padrĂŁo, o instalador do Trident implanta o operador no `trident` espaĂ§o de nomes.  Se o `trident` O namespace nĂŁo existe. Crie-o usando:
+
[listing]
----
kubectl apply -f deploy/namespace.yaml
----
* Para implantar o operador em um namespace diferente do `trident` namespace, atualizaĂ§ĂŁo `serviceaccount.yaml` , `clusterrolebinding.yaml` e `operator.yaml` e gere seu arquivo de pacote usando o `kustomization.yaml` .
+
.. Crie o `kustomization.yaml` usando o seguinte comando onde _<bundle.yaml>_ Ă© `bundle_pre_1_25.yaml` ou `bundle_post_1_25.yaml` com base na sua versĂŁo do Kubernetes.
+
[listing]
----
cp deploy/kustomization_<bundle.yaml> deploy/kustomization.yaml
----
.. Compile o pacote usando o seguinte comando, onde _<bundle.yaml>_ Ă© `bundle_pre_1_25.yaml` ou `bundle_post_1_25.yaml` com base na sua versĂŁo do Kubernetes.
+
[listing]
----
kubectl kustomize deploy/ > deploy/<bundle.yaml>
----




.Passos
. Crie os recursos e implemente o operador:
+
[listing]
----
kubectl create -f deploy/<bundle.yaml>
----
. Verifique se o operador, a implantaĂ§ĂŁo e os conjuntos de rĂ©plicas foram criados.
+
[listing]
----
kubectl get all -n <operator-namespace>
----



IMPORTANT: Deve haver apenas *uma instĂąncia* do operador em um cluster Kubernetes.  NĂŁo crie vĂĄrias instalaĂ§Ă”es do operador Trident .



=== Passo 4: Crie o `TridentOrchestrator` e instalar o Trident

Agora vocĂȘ pode criar o `TridentOrchestrator` e instale o Trident.  Opcionalmente, vocĂȘ podelink:kubernetes-customize-deploy.html["Personalize a sua instalaĂ§ĂŁo do Trident."] usando os atributos no `TridentOrchestrator` especificaĂ§ĂŁo.

[listing]
----
kubectl create -f deploy/crds/tridentorchestrator_cr.yaml
tridentorchestrator.trident.netapp.io/trident created

kubectl describe torc trident

Name:        trident
Namespace:
Labels:      <none>
Annotations: <none>
API Version: trident.netapp.io/v1
Kind:        TridentOrchestrator
...
Spec:
  Debug:     true
  Namespace: trident
  nodePrep:
  - iscsi
Status:
  Current Installation Params:
    IPv6:                      false
    Autosupport Hostname:
    Autosupport Image:         netapp/trident-autosupport:25.06
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:                     true
    Image Pull Secrets:
    Image Registry:
    k8sTimeout:           30
    Kubelet Dir:          /var/lib/kubelet
    Log Format:           text
    Silence Autosupport:  false
    Trident Image:        netapp/trident:25.06.0
  Message:                  Trident installed  Namespace:                trident
  Status:                   Installed
  Version:                  v25.06.0
Events:
    Type Reason Age From Message ---- ------ ---- ---- -------Normal
    Installing 74s trident-operator.netapp.io Installing Trident Normal
    Installed 67s trident-operator.netapp.io Trident installed
----


== Verifique a instalaĂ§ĂŁo

Existem vĂĄrias maneiras de verificar sua instalaĂ§ĂŁo.



=== Usando `TridentOrchestrator` status

O estado de `TridentOrchestrator` Indica se a instalaĂ§ĂŁo foi bem-sucedida e exibe a versĂŁo do Trident instalada.  Durante a instalaĂ§ĂŁo, o estado de `TridentOrchestrator` mudanĂ§as de `Installing` para `Installed` .  Se vocĂȘ observar o `Failed` status e o operador nĂŁo consegue se recuperar sozinho,link:../troubleshooting.html["Verifique os registros."] .

[cols="2"]
|===
| Status | DescriĂ§ĂŁo 


| InstalaĂ§ĂŁo | O operador estĂĄ instalando o Trident usando este sistema. `TridentOrchestrator` CR. 


| Instalado | O Trident foi instalado com sucesso. 


| Desinstalando | O operador estĂĄ desinstalando o Trident porque
`spec.uninstall=true` . 


| Desinstalado | O Trident foi desinstalado. 


| Fracassado | O operador nĂŁo conseguiu instalar, corrigir, atualizar ou desinstalar o Trident; o operador tentarĂĄ automaticamente recuperar-se deste estado.  Se esse estado persistir, serĂĄ necessĂĄrio solucionar o problema. 


| Atualizando | O operador estĂĄ atualizando uma instalaĂ§ĂŁo existente. 


| Erro | O `TridentOrchestrator` NĂŁo Ă© utilizado.  JĂĄ existe outro. 
|===


=== Usando o status de criaĂ§ĂŁo do pod

VocĂȘ pode confirmar se a instalaĂ§ĂŁo do Trident foi concluĂ­da verificando o status dos pods criados:

[listing]
----
kubectl get pods -n trident

NAME                                       READY   STATUS    RESTARTS   AGE
trident-controller-7d466bf5c7-v4cpw        6/6     Running   0           1m
trident-node-linux-mr6zc                   2/2     Running   0           1m
trident-node-linux-xrp7w                   2/2     Running   0           1m
trident-node-linux-zh2jt                   2/2     Running   0           1m
trident-operator-766f7b8658-ldzsv          1/1     Running   0           3m
----


=== Usando `tridentctl`

VocĂȘ pode usar `tridentctl` Para verificar a versĂŁo do Trident instalada.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 25.06.0        | 25.06.0        |
+----------------+----------------+
----