= Anotações e rótulos de namespace durante operações de restauração e failover
:allow-uri-read: 




== Anotações e rótulos de namespace durante operações de restauração e failover

Durante as operações de restauração e failover, os rótulos e anotações no namespace de destino são ajustados para corresponder aos rótulos e anotações no namespace de origem.  Rótulos ou anotações do namespace de origem que não existem no namespace de destino são adicionados, e quaisquer rótulos ou anotações já existentes são sobrescritos para corresponder ao valor do namespace de origem.  Rótulos ou anotações que existem apenas no espaço de nomes de destino permanecem inalterados.


NOTE: Se você usa o Red Hat OpenShift, é importante observar o papel crítico das anotações de namespace em ambientes OpenShift. As anotações de namespace garantem que os pods restaurados cumpram as permissões e configurações de segurança apropriadas definidas pelas restrições de contexto de segurança (SCCs) do OpenShift e possam acessar volumes sem problemas de permissão. Para mais informações, consulte o https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/authentication_and_authorization/managing-pod-security-policies["Documentação sobre restrições de contexto de segurança do OpenShift"^] .

Você pode impedir que anotações específicas no namespace de destino sejam sobrescritas definindo a variável de ambiente do Kubernetes. `RESTORE_SKIP_NAMESPACE_ANNOTATIONS` antes de executar a operação de restauração ou failover. Por exemplo:

[source, console]
----
helm upgrade trident-protect --set restoreSkipNamespaceAnnotations=<annotation_key_to_skip_1>,<annotation_key_to_skip_2> --reuse-values
----

NOTE: Ao executar uma operação de restauração ou failover, quaisquer anotações e rótulos de namespace especificados em `restoreSkipNamespaceAnnotations` e `restoreSkipNamespaceLabels` são excluídos da operação de restauração ou failover. Certifique-se de que essas configurações sejam definidas durante a instalação inicial do Helm. Para saber mais, consulte link:../trident-protect/trident-protect-customize-installation.html#configure-autoSupport-and-namespace-filtering-options["Configurar opções de filtragem de namespace e AutoSupport"].

Se você instalou o aplicativo de origem usando o Helm com o `--create-namespace` bandeira, tratamento especial é dado ao `name` Legenda da etiqueta.  Durante o processo de restauração ou failover, o Trident Protect copia esse rótulo para o namespace de destino, mas atualiza o valor para o valor do namespace de destino se o valor da origem corresponder ao namespace de origem.  Se esse valor não corresponder ao namespace de origem, ele será copiado para o namespace de destino sem alterações.



=== Exemplo

O exemplo a seguir apresenta um namespace de origem e um de destino, cada um com anotações e rótulos diferentes.  É possível visualizar o estado do namespace de destino antes e depois da operação, bem como a forma como as anotações e os rótulos são combinados ou sobrescritos no namespace de destino.



==== Antes da operação de restauração ou failover

A tabela a seguir ilustra o estado dos namespaces de origem e destino do exemplo antes da operação de restauração ou failover:

[cols="1,2a,2a"]
|===
| Espaço de nomes | Anotações | Etiquetas 


| Espaço de nomes ns-1 (fonte)  a| 
* anotação.um/chave: "valoratualizado"
* anotação.dois/chave: "verdadeiro"

 a| 
* ambiente=produção
* conformidade=hipaa
* nome=ns-1




| Espaço de nomes ns-2 (destino)  a| 
* anotação.um/chave: "verdadeiro"
* anotação.três/chave: "falso"

 a| 
* função=banco de dados


|===


==== Após a operação de restauração

A tabela a seguir ilustra o estado do namespace de destino de exemplo após a operação de restauração ou failover.  Algumas chaves foram adicionadas, outras foram sobrescritas, e a `name` O rótulo foi atualizado para corresponder ao namespace de destino:

[cols="1,2a,2a"]
|===
| Espaço de nomes | Anotações | Etiquetas 


| Espaço de nomes ns-2 (destino)  a| 
* anotação.um/chave: "valoratualizado"
* anotação.dois/chave: "verdadeiro"
* anotação.três/chave: "falso"

 a| 
* nome=ns-2
* conformidade=hipaa
* ambiente=produção
* função=banco de dados


|===