---
sidebar: sidebar 
permalink: trident-concepts/vol-access-groups.html 
keywords: volume access groups, element, solidfire, chap, Trident, hci, netapp hci, storage system, access volumes, 
summary: Saiba mais sobre como o Trident utiliza grupos de acesso por volume. 
---
= Grupos de acesso a volume
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre como a Trident utiliza https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["grupos de acesso a volume"^] .


NOTE: Ignore esta seção se estiver usando o CHAP, que é recomendado para simplificar o gerenciamento e evitar o limite de escalabilidade descrito abaixo.  Além disso, se você estiver usando o Trident no modo CSI, pode ignorar esta seção.  O Trident utiliza o CHAP quando instalado como um provisionador CSI aprimorado.



== Saiba mais sobre grupos de acesso por volume

O Trident pode usar grupos de acesso a volumes para controlar o acesso aos volumes que provisiona.  Se o CHAP estiver desativado, espera-se encontrar um grupo de acesso chamado `trident` a menos que você especifique um ou mais IDs de grupo de acesso na configuração.

Embora o Trident associe novos volumes aos grupos de acesso configurados, ele não cria nem gerencia os próprios grupos de acesso.  Os grupos de acesso devem existir antes da adição do backend de armazenamento ao Trident e precisam conter os IQNs iSCSI de todos os nós do cluster Kubernetes que possam potencialmente montar os volumes provisionados por esse backend.  Na maioria das instalações, isso inclui todos os nós de trabalho do cluster.

Para clusters Kubernetes com mais de 64 nós, você deve usar vários grupos de acesso.  Cada grupo de acesso pode conter até 64 IQNs, e cada volume pode pertencer a quatro grupos de acesso.  Com o máximo de quatro grupos de acesso configurados, qualquer nó em um cluster de até 256 nós poderá acessar qualquer volume.  Para obter os limites mais recentes para grupos de acesso por volume, consulte https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["aqui"^] .

Se você estiver modificando a configuração de uma que esteja usando a configuração padrão. `trident` Para acessar um grupo que também utiliza outros, inclua o ID do grupo. `trident` grupo de acesso na lista.
