---
sidebar: sidebar 
permalink: trident-reco/backup.html 
keywords: data protection, replication, dr, disaster recovery, snapmirror, back up, snapshot, element, volume replication 
summary: Saiba mais sobre as opções de proteção e recuperação para o Trident e para os volumes criados com o Trident.  Você deve ter uma estratégia de proteção e recuperação de dados para cada aplicação que exija persistência. 
---
= Proteção de dados e recuperação de desastres
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Saiba mais sobre as opções de proteção e recuperação para o Trident e para os volumes criados com o Trident.  Você deve ter uma estratégia de proteção e recuperação de dados para cada aplicação que exija persistência.



== Replicação e recuperação do Trident

Você pode criar um backup para restaurar o Trident em caso de desastre.



=== Replicação do Trident

O Trident usa CRDs do Kubernetes para armazenar e gerenciar seu próprio estado e o cluster Kubernetes etcd para armazenar seus metadados.

.Passos
. Faça backup do cluster Kubernetes etcd usandolink:https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#backing-up-an-etcd-cluster["Kubernetes: Fazendo backup de um cluster etcd"^] .
. Coloque os artefatos de backup em um FlexVol volume.
+

NOTE: A NetApp recomenda que você proteja a SVM onde o FlexVol reside com uma relação SnapMirror com outra SVM.





=== Recuperação Trident

Utilizando CRDs do Kubernetes e o snapshot do etcd do cluster Kubernetes, você pode recuperar o Trident.

.Passos
. A partir da SVM de destino, monte o volume que contém os arquivos de dados e certificados do Kubernetes etcd no host que será configurado como nó mestre.
. Copie todos os certificados necessários referentes ao cluster Kubernetes em `/etc/kubernetes/pki` e os arquivos de membro do etcd em `/var/lib/etcd` .
. Restaure o cluster Kubernetes a partir do backup do etcd usandolink:https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/#restoring-an-etcd-cluster["Kubernetes: Restaurando um cluster etcd"^] .
. Correr `kubectl get crd` Para verificar se todos os recursos personalizados do Trident foram ativados e recuperar os objetos do Trident para confirmar se todos os dados estão disponíveis.




== Replicação e recuperação de SVM

O Trident não consegue configurar relações de replicação; no entanto, o administrador de armazenamento pode usar https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-concept.html["ONTAP SnapMirror"^] para replicar uma SVM.

Em caso de desastre, você pode ativar o SVM de destino do SnapMirror para começar a fornecer dados.  Você poderá retornar ao servidor primário quando os sistemas forem restaurados.

.Sobre esta tarefa
Ao usar o recurso de replicação SVM do SnapMirror, considere o seguinte:

* Você deve criar um backend distinto para cada SVM com SVM-DR habilitado.
* Configure as classes de armazenamento para selecionar os backends replicados somente quando necessário, evitando assim o provisionamento de volumes que não precisam de replicação nos backends que suportam SVM-DR.
* Os administradores de aplicativos devem compreender o custo e a complexidade adicionais associados à replicação e considerar cuidadosamente seu plano de recuperação antes de iniciar esse processo.




=== Replicação SVM

Você pode usarlink:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-svm-replication-workflow-concept.html["ONTAP: Replicação SnapMirror SVM"^] para criar a relação de replicação SVM.

O SnapMirror permite que você defina opções para controlar o que será replicado.  Você precisará saber quais opções selecionou ao realizar a operação.<<Recuperação de SVM usando Trident>> .

* link:https://docs.netapp.com/us-en/ontap/data-protection/replicate-entire-svm-config-task.html["-preservar identidade verdadeiro"^]replica toda a configuração da SVM.
* link:https://docs.netapp.com/us-en/ontap/data-protection/exclude-lifs-svm-replication-task.html["-descartar-configurações rede"^]Exclui LIFs e configurações de rede relacionadas.
* link:https://docs.netapp.com/us-en/ontap/data-protection/exclude-network-name-service-svm-replication-task.html["-preservar identidade falso"^]replica apenas os volumes e a configuração de segurança.




=== Recuperação de SVM usando Trident

O Trident não detecta automaticamente falhas no SVM.  Em caso de desastre, o administrador pode iniciar manualmente o failover do Trident para a nova SVM.

.Passos
. Cancele as transferências SnapMirror agendadas e em andamento, interrompa a relação de replicação, pare o SVM de origem e, em seguida, ative o SVM de destino do SnapMirror .
. Se você especificou `-identity-preserve false` ou `-discard-config network` Ao configurar a replicação do seu SVM, atualize o `managementLIF` e `dataLIF` no arquivo de definição do backend Trident .
. Confirmar `storagePrefix` está presente no arquivo de definição do backend Trident .  Este parâmetro não pode ser alterado.  omitindo `storagePrefix` fará com que a atualização do backend falhe.
. Atualize todos os backends necessários para refletir o novo nome da SVM de destino usando:
+
[listing]
----
./tridentctl update backend <backend-name> -f <backend-json-file> -n <namespace>
----
. Se você especificou `-identity-preserve false` ou `discard-config network` Você deve reiniciar todos os pods da aplicação.
+

NOTE: Se você especificou `-identity-preserve true` Todos os volumes provisionados pelo Trident começam a fornecer dados quando o SVM de destino é ativado.





== Replicação e recuperação de volume

O Trident não consegue configurar relações de replicação SnapMirror ; no entanto, o administrador de armazenamento pode usarlink:https://docs.netapp.com/us-en/ontap/data-protection/snapmirror-disaster-recovery-concept.html["Replicação e recuperação do SnapMirror do ONTAP"^] para replicar volumes criados pelo Trident.

Em seguida, você pode importar os volumes recuperados para o Trident usandolink:../trident-use/vol-import.html["importação de volume tridentctl"] .


NOTE: A importação não é suportada em `ontap-nas-economy` , `ontap-san-economy` , ou `ontap-flexgroup-economy` motoristas.



== Proteção de dados instantâneos

Você pode proteger e restaurar dados usando:

* Um controlador de snapshots externo e CRDs para criar snapshots de volumes persistentes (PVs) do Kubernetes.
+
link:../trident-use/vol-snapshots.html["Instantâneos de volume"]

* Os snapshots do ONTAP permitem restaurar todo o conteúdo de um volume ou recuperar arquivos ou LUNs individuais.
+
link:https://docs.netapp.com/us-en/ontap/data-protection/manage-local-snapshot-copies-concept.html["Capturas instantâneas do ONTAP"^]


