---
sidebar: sidebar 
permalink: trident-protect/learn-about-trident-protect.html 
keywords: overview, concepts, features, use case, workloads, how workload factory works 
summary: O Trident Protect permite proteger seus aplicativos e dados de aplicativos usando o Trident. 
---
= Saiba mais sobre a proteção Trident.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
O NetApp Trident Protect fornece recursos avançados de gerenciamento de dados de aplicativos que aprimoram a funcionalidade e a disponibilidade de aplicativos Kubernetes com estado, apoiados pelos sistemas de armazenamento NetApp ONTAP e pelo provisionador de armazenamento NetApp Trident CSI. O Trident Protect simplifica o gerenciamento, a proteção e a movimentação de cargas de trabalho em contêineres entre nuvens públicas e ambientes locais. Ele também oferece recursos de automação por meio de sua API e CLI.

Você pode proteger aplicativos com o Trident Protect criando recursos personalizados (CRs) ou usando a CLI do Trident Protect.



== O que vem a seguir?

Você pode se informar sobre os requisitos do Trident Protect antes de instalá-lo:

* link:trident-protect-requirements.html["Requisitos de proteção Trident"]

