---
sidebar: sidebar 
permalink: trident-protect/trident-protect-generate-support-bundle.html 
keywords: trident, protect, bundle, support, netapp, custom, resource, file 
summary: 'O Trident Protect permite que os administradores gerem pacotes que incluem informações úteis para o Suporte da NetApp , incluindo logs, métricas e informações de topologia sobre os clusters e aplicativos sob gerenciamento. Se você estiver conectado à Internet, poderá enviar pacotes de suporte para o site de suporte da NetApp (NSS) usando um arquivo de recurso personalizado (CR).' 
---
= Gere um pacote de suporte Trident Protect.
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O Trident Protect permite que os administradores gerem pacotes que incluem informações úteis para o Suporte da NetApp , incluindo logs, métricas e informações de topologia sobre os clusters e aplicativos sob gerenciamento. Se você estiver conectado à Internet, poderá carregar pacotes de suporte no NetApp Support Site (NSS) usando um arquivo de recurso personalizado (CR).

[role="tabbed-block"]
====
.Crie um pacote de suporte usando uma solicitação de crédito (CR).
--
.Passos
. Crie o arquivo de recurso personalizado (CR) e dê um nome a ele (por exemplo, `trident-protect-support-bundle.yaml` ).
. Configure os seguintes atributos:
+
** *metadata.name*: (_Obrigatório_) O nome deste recurso personalizado; escolha um nome único e adequado ao seu ambiente.
** *spec.triggerType*: (_Obrigatório_) Determina se o pacote de suporte é gerado imediatamente ou agendado.  A geração programada de pacotes ocorre às 00h UTC.  Valores possíveis:
+
*** Agendado
*** Manual


** *spec.uploadEnabled*: (Opcional) Controla se o pacote de suporte deve ser carregado no site de suporte da NetApp após ser gerado.  Se não for especificado, o valor padrão é `false` .  Valores possíveis:
+
*** verdadeiro
*** falso (padrão)


** *spec.dataWindowStart*: (Opcional) Uma string de data no formato RFC 3339 que especifica a data e a hora em que a janela de dados incluída no pacote de suporte deve começar.  Caso não seja especificado, o padrão é de 24 horas atrás.  A data mais antiga que você pode especificar é de 7 dias atrás.
+
Exemplo de YAML:

+
[source, yaml]
----
---
apiVersion: protect.trident.netapp.io/v1
kind: AutoSupportBundle
metadata:
  name: trident-protect-support-bundle
spec:
  triggerType: Manual
  uploadEnabled: true
  dataWindowStart: 2024-05-05T12:30:00Z
----


. Depois de preencher o `trident-protect-support-bundle.yaml` Arquivo com os valores corretos, aplique o CR:
+
[source, console]
----
kubectl apply -f trident-protect-support-bundle.yaml -n trident-protect
----


--
.Crie um pacote de suporte usando a CLI
--
.Passos
. Crie o pacote de suporte, substituindo os valores entre colchetes pelas informações do seu ambiente.  O `trigger-type` Determina se o pacote é criado imediatamente ou se o tempo de criação é ditado pelo agendamento, e pode ser `Manual` ou `Scheduled` .  A configuração padrão é `Manual` .
+
Por exemplo:

+
[source, console]
----
tridentctl-protect create autosupportbundle <my-bundle-name> --trigger-type <trigger-type> -n trident-protect
----


--
====


== Monitore e recupere o pacote de suporte

Depois de criar um pacote de suporte usando qualquer um dos métodos, você pode monitorar seu progresso de geração e recuperá-lo para seu sistema local.

.Passos
. Espere pelo `status.generationState` para alcançar `Completed` estado. Você pode monitorar o progresso da geração com o seguinte comando:
+
[source, console]
----
kubectl get autosupportbundle trident-protect-support-bundle -n trident-protect
----
. Recupere o pacote de suporte para seu sistema local. Obtenha o comando de cópia do pacote AutoSupport concluído:
+
[source, console]
----
kubectl describe autosupportbundle trident-protect-support-bundle -n trident-protect
----
+
Encontre o `kubectl cp` Extraia o comando da saída e execute-o, substituindo o argumento de destino pelo diretório local de sua preferência.


